---
- apt: pkg=openvpn state=present
- apt: pkg=easy-rsa state=present

- set_fact:
    easyrsa=/my/proj/ansible/roles/openvpn_server/easy-rsa/easyrsa3/easyrsa
    openvpn_log_dir=/var/log
    remote={{ inventory_hostname }}
    vpn_net={{ ['vpn_ext', 'vpn_home'][vpn_remote_addr.startswith('10.4.')] }}
- set_fact:
    vpn_network={{ dict(vpn_ext='10.3.0.0', vpn_home='10.4.0.0')[vpn_net] }}
    vpn_netmask=255.255.255.0
    vpn_net_name={{vpn_net}}_{{inventory_hostname}}
    vpn_root_dir=/my/proj/ansible/roles/openvpn_server/files/{{vpn_net}}
    vpn_config_dir=/etc/openvpn/{{vpn_net}}
    
- name: make new client key
  delegate_to: bang
  shell: "EASYRSA_REQ_CN={{vpn_net_name}} {{easyrsa}}  --batch gen-req {{ vpn_net_name }} nopass"
  args:
    chdir: "{{vpn_root_dir}}"
    creates: "{{vpn_root_dir}}/pki/private/{{vpn_net_name}}.key"
    
- name: sign client key
  delegate_to: bang
  shell: "{{easyrsa}}  --batch sign-req client {{vpn_net_name}}"
  args:
    chdir: "{{vpn_root_dir}}"
    creates: "{{vpn_root_dir}}/pki/issued/{{vpn_net_name}}.crt"



- file: path={{vpn_config_dir}} state=directory
    
- copy:
    dest={{vpn_config_dir}}/ca.crt
    src={{vpn_root_dir}}/pki/ca.crt
    owner=root
    group=root
    mode=0644
  notify: openvpn restart
    
- template:
    dest=/etc/openvpn/{{ vpn_net_name }}.conf
    src=local.conf.j2
    owner=root
    group=root
  notify: openvpn restart

- name: install tls-auth
  copy:
    dest={{vpn_config_dir}}/ta.key
    src={{vpn_root_dir}}/ta.key
    owner=root
    group=root
    mode=0600
  notify: openvpn restart
 
- name: install key
  copy:
    dest={{vpn_config_dir}}/{{ vpn_net_name }}.key
    src={{vpn_root_dir}}/pki/private/{{vpn_net_name}}.key
    owner=root
    group=root
    mode=0600
  notify: openvpn restart

- name: install crt
  copy:
    dest={{vpn_config_dir}}/{{ vpn_net_name }}.crt
    src={{vpn_root_dir}}/pki/issued/{{vpn_net_name}}.crt
    owner=root
    group=root
    mode=0600
  notify: openvpn restart

- name: enable openvpn
  lineinfile:
    path=/etc/default/openvpn
    regexp='AUTOSTART="all"'
    line='AUTOSTART="all"'
  notify: openvpn restart

- shell: systemctl daemon-reload
- shell: systemctl restart openvpn
  
- name: write server-side config to give client a fixed address on prime
  # doesn't work to use the name 'prime' here- ansible ignores the
  # ansible_ssh_host setting
  delegate_to: public.bigasterisk.com
  copy:
    dest="{{ vpn_config_dir }}/client/{{vpn_net_name}}"
    content="ifconfig-push {{ vpn_remote_addr }} {{vpn_network}}"
  notify: openvpn restart
  when: vpn_net == 'vpn_ext'

- name: write server-side config to give client a fixed address on bang
  delegate_to: bang
  copy:
    dest="{{ vpn_config_dir }}/client/{{vpn_net_name}}"
    content="ifconfig-push {{ vpn_remote_addr }} {{vpn_network}}"
  notify: openvpn restart
  when: "vpn_net == 'vpn_home'"

  
