---

- copy: dest=/opt/docker_registry/config.yml src=config.yml

- lineinfile: path=/etc/resolv.conf regex="8\.8\.8\.8" line="nameserver 8.8.8.8"
  
- docker_container:
    name: registry
    image: "registry:2"
    published_ports: 5000:5000
    volumes:
      - "/opt/docker_registry/registry:/var/lib/registry/docker/registry"
      - "/opt/docker_registry/config.yml:/etc/docker/registry/config.yml"
    restart_policy: always
    memory: "10M"
    restart: "yes"

- lineinfile: path=/etc/resolv.conf regex="8\.8\.8\.8" line="#nameserver 8.8.8.8"
