---

- file: path=/var/lib/ruler.d state=directory
- command: /my/proj/ruler/bin/python /my/proj/ruler/siteconf2ruler.py /var/lib/ruler.d/sites.n3


  
- supervisor_process_mod:
    name=ruler_reloader
    directory=/my/proj/ruler
    command="/my/proj/ruler/bin/python /my/proj/ruler/reloader.py"
    user=drewp
  notify:
   - supervisord update

- apt: pkg=libleveldb1
- file: path=/opt/ruler/server_store state=directory owner=drewp
- supervisor_process_mod:
    name=ruler_server_8102
    directory=/my/proj/ruler/server
    command="/my/proj/ruler/bin/python /my/proj/ruler/server/server.py"
    user=drewp
  notify:
   - supervisord update

- supervisor_process_mod:
    name=ruler_analysis_8103
    directory=/my/proj/ruler/analysis
    command="/my/proj/ruler/bin/python /my/proj/ruler/analysis/analysis.py"
    user=drewp
  notify:
   - supervisord update
