---

- apt: deb=https://dl.influxdata.com/influxdb/releases/influxdb_1.1.0_amd64.deb
- service: name=influxdb state=stopped enabled=no
  
- copy: src=influxdb.conf dest=/etc/influxdb/influxdb.conf
- file: path="/opt/influxdb" state=directory owner=influxdb
  
- supervisor_process_mod:
    name=influxdb_9060
    directory=/opt/influxdb
    autostart=true
    startretries=3
    user=influxdb
    command="/usr/bin/influxd -config /etc/influxdb/influxdb.conf"
  notify: supervisord update

