---
- set_fact: job=influxdb port=9060 image_tag="latest"
- set_fact: base_image_platform="{{'pi' if ansible_architecture=='armv7l' else 'x86'}}"
- set_fact: image=bang6:5000/{{job}}_{{base_image_platform}}:{{image_tag}}
- docker_image: name={{image}} force=yes

- supervisor_process_mod:
    name="{{job}}_{{port}}"
    command="docker run --rm --name {{job}} -v /opt/influxdb:/opt/influxdb -p {{port}}:{{port}} {{image}}"
  notify: supervisord update

