---
- set_fact: top=/opt/python-openzwave
  
- file: dest={{top}} state=directory owner=drewp

- git: repo=https://github.com/OpenZWave/python-openzwave.git version=d2e14eae4a249d09a0148582fb556c27c42eed13 dest={{top}}
  
#- hg: repo=https://code.google.com/p/python-openzwave/ dest={{top}}
#- subversion: repo=http://open-zwave.googlecode.com/svn/trunk/ dest={{top}}/openzwave
#
#- command: chown -R drewp {{top}}
#  
#- command: sudo -u drewp make chdir={{top}}/openzwave/cpp/build creates={{top}}/openzwave/cpp/build/libopenzwave.a
#- file: src={{top}}/openzwave/cpp/build/libopenzwave.a dest={{top}}/openzwave/libopenzwave.a state=link
#  
#- command: sudo -u drewp virtualenv . chdir={{top}} creates={{top}}/bin/python
#- command: sudo -u drewp bin/pip install cython==0.14 chdir={{top}} creates={{top}}/lib/python2.7/site-packages/cython.py
#- command: sudo -u drewp {{top}}/bin/python setup-lib.py install chdir={{top}}
#- command: sudo -u drewp {{top}}/bin/python setup-api.py install chdir={{top}}
#


- file: dest={{top}}/env state=directory owner=drewp


#  python3 build not working:
#- apt: pkg=python3-pip
#- apt: pkg=python3-docutils
#- apt: pkg=python3-dev
#- apt: pkg=python3-setuptools
#- apt: pkg=cython3 
#- command: sudo -u drewp /usr/bin/python3 /usr/lib/python3/dist-packages/virtualenv.py --python=/usr/bin/python3 {{top}}/env/ creates={{top}}/env/bin/python

- apt: pkg=python-pip
- apt: pkg=python-docutils
- apt: pkg=python-dev
- apt: pkg=python-setuptools
- apt: pkg=cython 
- command: virtualenv {{top}}/env/ creates={{top}}/env/bin/python

- pip: name=nose-html        executable={{top}}/env/bin/pip
- pip: name=nose-progressive executable={{top}}/env/bin/pip
- pip: name=coverage         executable={{top}}/env/bin/pip
- pip: name=nose             executable={{top}}/env/bin/pip
- pip: name=pylint           executable={{top}}/env/bin/pip
- pip: name=pydispatcher     executable={{top}}/env/bin/pip
- pip: name=cython           executable={{top}}/env/bin/pip
  

- command: sudo -u drewp make build chdir={{top}} creates={{top}}/openzwave/libopenzwave.a

- command: env/bin/python setup-lib.py build chdir={{top}}
  