---
- set_fact: top=/opt/python-openzwave
  
- apt: pkg=python-dev
- file: dest={{top}} state=directory owner=drewp

- hg: repo=https://code.google.com/p/python-openzwave/ dest={{top}}
- subversion: repo=http://open-zwave.googlecode.com/svn/trunk/ dest={{top}}/openzwave

- command: chown -R drewp {{top}}
  
- command: sudo -u drewp make chdir={{top}}/openzwave/cpp/build creates={{top}}/openzwave/cpp/build/libopenzwave.a
- file: src={{top}}/openzwave/cpp/build/libopenzwave.a dest={{top}}/openzwave/libopenzwave.a state=link
  
- command: sudo -u drewp virtualenv . chdir={{top}} creates={{top}}/bin/python
- command: sudo -u drewp bin/pip install cython==0.14 chdir={{top}} creates={{top}}/lib/python2.7/site-packages/cython.py
- command: sudo -u drewp {{top}}/bin/python setup-lib.py install chdir={{top}}
- command: sudo -u drewp {{top}}/bin/python setup-api.py install chdir={{top}}
