---
- user: name=grafana
- file: path=/opt/grafana state=directory owner=grafana
- apt: deb=https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_4.3.2_amd64.deb 
- service: name=grafana enabled=no

- copy: dest=/etc/grafana/grafana.ini src=grafana.ini

# rest of site is over in websites.yml
