---

# now running everything as root; no sudo, no typing passwords

# test connections:
#  ansible all -m ping -vvv

# to prepare a host, aptitude install python-apt python-pip python-pycurl python-keyczar
# to run this:
#  ansible-playbook site.yml 
#  ansible-playbook site.yml -l dash --tags gitannex

# supervisord is installed as a dependency. put meta/main.yml in those roles
    
- hosts: all
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: ppa, tags: ['ppa']}
    - {role: supdebug, tags: ['supdebug']}
    - {role: cjdns, tags: ['cjdns']}
  tasks:
    - apt: pkg=djbdns state=present
      tags: ['djbdns']
      when: inventory_hostname != "sticker"
  
- hosts: big
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: nodejs, tags: ['nodejs']}
    - {role: bigasterisk_users, tags: ['bigasterisk_users']}
    - {role: unison, tags: ['unison']}
  tasks:
    - name: no UseDNS on ssh server
      lineinfile: dest=/etc/ssh/sshd_config regexp="^UseDNS\b" line="UseDNS no"
      notify: sshd restart

- hosts: prime
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: supervisor_at_boot, tags: ['supervisor_at_boot']}
    - {role: bigasterisk_users, tags: ['bigasterisk_users']}
    - {role: nginx_ssl_certs, tags: ['nginx_forward', 'nginx_ssl_certs']}
    - {role: nginx_forward, tags: ['nginx_forward', 'nginx_server']}
    - {role: nginx_static_data, tags: ['nginx_forward', 'nginx_static_data']}
    - {role: postfix, tags: ['postfix']}
    - {role: dovecot, tags: ['dovecot']}
    - {role: docker, tags: ['docker']}
    - {role: map_mqtt_receiver, tags: ['map_mqtt_receiver']}
    - {role: openvpn_server, tags: ['openvpn_server']}
#    - {role: openvpn_bling_server, tags: ['openvpn_bling_server']}
    - {role: prime_firewall, tags: ['prime_firewall']}
  tasks:
    - hostname: name=prime

- hosts: bang
  gather_facts: no
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: x_bang, tags: ['x_bang']}
    - {role: sesame, tags: ['sesame']}
# for phone talking to bigasterisk.com at home
    - {role: map_mqtt_receiver, tags: ['map_mqtt_receiver']}
    - {role: checkvistpost, tags: ['checkvistpost']}
    - {role: supervisord_local, tags: ['supervisord_local']}
    - {role: photo, tags: ['photo']}
    - {role: network_bigasterisk_gateway, tags: ['network_bigasterisk_gateway']}
    - {role: nginx_ssl_certs, tags: ['nginx_ssl_certs']}
    - {role: dropbox, tags: ['dropbox']}
#    - {role: openvpn_server, tags: ['openvpn_server']}
    - {role: dovecot_home, tags: ['dovecot_home']}
#    - {role: usbReset, tags: ['usbReset']}
    - {role: ruler, tags: ['ruler']}
    - {role: ruler_server, tags: ['ruler']}
    - {role: ruler_client, tags: ['ruler']}
    - {role: ajaxterm, tags: ['ajaxterm']}
    - {role: collectd, tags: ['collectd']}
    - {role: graphite, tags: ['graphite']}
    - {role: minetest_server, tags: ['minetest_server']}
    - {role: cups, tags: ['cups']}
    
  tasks:
    - apt_repository: repo=ppa:nginx/stable
      tags: ['nginx']
    # breaking, needs review
    #- apt: update_cache=yes pkg=nginx=1.6.2-5+trusty0 state=present
    #  tags: ['nginx']
    - name: do not use init.d to launch nginx
      service: name=nginx enabled=no
      tags: ['nginx']
    - include: tasks/bang_processes.yml
    - include: tasks/bang_processes_map.yml
    - include: tasks/bang_sites.yml

- include: websites.yml
      
- hosts: dash
  gather_facts: no
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: cups, tags: ['cups']}
    - {role: supervisor_at_boot, tags: ['supervisor_at_boot']}
#    - {role: gitannex, tags: ["gitannex"]}
    - {role: mail_relay, tags: ['mail_relay']}
#    - photo_worker # not without nfs
    - {role: ruler_server, tags: ['ruler']}
    - {role: ruler_client, tags: ['ruler']}
  tasks:
    - include: tasks/dash_processes.yml

- hosts: slash
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: supervisor_at_boot, tags: ['supervisor_at_boot']}
    - photo_worker
    - usbReset
    - { role: webcam, camName: 'c0', port: 9020, config: 'slash.json' }
    - { role: webcam, camName: 'frontDoor', port: 9023, config: 'slash4.json' }
    - { role: webcam, camName: 'livingRoom', port: 9025, config: 'slash5.json' }
  tasks:
    - include: tasks/slash_processes.yml

- hosts: plus
  gather_facts: no
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: bigasterisk_users, tags: ['bigasterisk_users']}
    - {role: supervisor_at_boot, tags: ['supervisor_at_boot']}
    - {role: laptop_x11, tags: ['laptop_x11']}

- hosts: brace
  gather_facts: no
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: supervisor_at_boot, tags: ['supervisor_at_boot']}
    - {role: openzwave, tags: ['openzwave']}
    - {role: openzwave_lightctl, tags: ['openzwave_lightctl']}
    - {role: ari_room_screen, tags: ['ari_room_screen']}

- hosts: star
  handlers:
    - include: handlers/main.yml
  roles:
    - { role: webcam, camName: 'printer', port: 9016, config: 'star.json', tags: ['webcam'] }
  tasks:
    - include: tasks/star_processes.yml
      
- hosts: stor
  gather_facts: no
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: network_stor, tags: ['network_stor']}
    - {role: zfs_server, tags: ['zfs_server']}
    - {role: zfs_monitorable, tags: ['zfs_monitorable']}
    - {role: zfs_auto_snapshot, tags: ['zfs_auto_snapshot']}
    - {role: bigasterisk_users, tags: ['bigasterisk_users']}

- hosts: grapes
  gather_facts: no
  handlers:
    - include: handlers/main.yml
  roles:
    - boot2gecko
    - rpi_buttons

- hosts: bling
  gather_facts: no
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: openvpn_client, tags: ['openvpn_client']}

- hosts: sticker
  gather_facts: no
  tasks:
    - user: name=pi uid=1000 group=7 groups=lp,adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,netdev,i2c,input,spi,gpio,fuse
    - user: name=drewp uid=501 group=1000 groups=lp,adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,netdev,i2c,input,spi,gpio,fuse
    - supervisor_process_mod:
        name=piNode_9059
        user=pi
        directory=/home/pi/bang/my/proj/homeauto/service/piNode
        command=/home/pi/bang/my/proj/homeauto/service/piNode/bin/python piNode.py
      notify:
        - supervisord update
  roles:
    - {role: supervisor_at_boot, tags: ['supervisor_at_boot']}
    - {role: raspi_bluetooth_speaker, tags: ['raspi_bluetooth_speaker']}
    - {role: pigpio, tags: ['pigpio']}
    - {role: raspi_io_node, tags: ['io_node']}    

- hosts: with_speakers
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: pulse, tags: ['pulse']}
    - {role: mpd, tags: ['mpd']}
    - {role: ympd, tags: ['ympd']}
    - {role: speech_music, tags: ['speech_music']}
    - {role: mpdweb, tags: ['mpdweb']}
    # - mpdpandorafeeder # not working yet

- hosts: with_x11
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: homeauto_dpms, tags: ['homeauto_dpms']}
    - {role: homeauto_xidle, tags: ['homeauto_xidle']}

- hosts: with_removable_storage
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: auto_mount_removable, tags: ['auto_mount_removable']}
    
- hosts: nfs_server:nfs_client
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: photo_fileschangedpost, tags: ['photo_fileschangedpost']}

- hosts: nfs_client
  handlers:
    - include: handlers/main.yml
  tasks:
    - apt: pkg=nfs-common state=present
    - mount:
        fstype=nfs
        name=/my
        src=10.1.0.2:/stor6/my
        state=mounted
        
- hosts: sshfs_client
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: my_sshfs, tags: ['my_sshfs']}


- hosts: vpn_client
  #gather_facts: no
  handlers:
    - include: handlers/main.yml
  roles:
    - {role: openvpn_client, tags: ['openvpn_client']}

