---
- hosts: bang
  gather_facts: no
  handlers:
    - include: handlers/main.yml
  tags: ['sites']
  tasks:
    # for homepage
    - apt: pkg=darcs
    - apt: pkg=xsltproc
    # for arduinonode
    - apt: pkg=arduino-mk
    - apt: pkg=indent
    # for heist
    - apt: pkg=uuid-runtime
    # for blog feeds
    - apt: pkg=python-dateutil
    # for firedata
    - apt: pkg=coffeescript
  roles:
    - role: site
      site_name: 'heist_querytransactions'
      internalPort: "10003"
      path: "/heist/"
      openid: "admin"
      serverHost: "bang"
      process:
        directory: "/my/proj/heist"
        command: "/my/proj/heist/bin/python querytransactions.py"
        
    - role: site
      site_name: 'darcsweb'
      path: "/darcs/"
      openid: "anonymous"
      serverHost: "bang"
      internalPort: "8004"
      root_page_timeout_secs: 10
      process:
        directory: "/my/site/darcsweb"
        command: "nice /my/site/darcsweb/serve"
        user: "darcsweb"
    
    - role: site
      site_name: 'href'
      path: "/href/"
      openid: "anonymous"
      serverHost: "bang"
      internalPort: "10002"
      process:
        directory: "/my/proj/href"
        command: "/my/proj/href/run"

#    - role: site
#      name: 'thermostat'
#      path: "/thermostat/"
#      openid: "admin"
#      serverHost: "bang"
#      accessLog: false
#      internalPort: "10001"
#      process:
#        directory: "/my/proj/homeauto/service/thermostat"
#        command: "/my/proj/homeauto/service/thermostat/bin/python thermostat.py"

    - role: site
      tags: ['babysitcoop']
      site_name: 'babysitcoop'
      path: "/babysitcoop/"
      openid: "anonymous"
      serverHost: "bang"
      internalPort: "3002"
      process:
        directory: "/my/proj/babysitcoop"
        command: "/my/proj/babysitcoop/bin/python babysitcoop.py"

    - role: site
      tags: ['babysitcoop']
      site_name: 'babysitcoop_jm'
      path: "/jmbc/"
      openid: "anonymous"
      serverHost: "bang"
      internalPort: "3004"
      process:
        directory: "/my/proj/babysitcoop_jm"
        environment: "BABYSIT_INSTANCE=jm"
        command: "/my/proj/babysitcoop/bin/python babysitcoop.py"
        
    - role: site
      site_name: 'bigfoaf'
      tags: ['bigfoaf']
      path: "/foaf/"
      upstreamPath: "/foaf/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "3003"
      process:
        directory: "/my/proj/bigfoaf"
        command: "/my/proj/bigfoaf/bin/python bigfoaf.py"
        
    - role: site
      site_name: 'bigfoaf_logins'
      tags: ['bigfoaf']
      path: "/logins/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "10007"
      process:
        directory: "/my/proj/bigfoaf"
        command: "/my/proj/bigfoaf/bin/python logins.py"
        
    - role: site
      site_name: 'diarybot'
      path: "/diary/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "9048" # also talks jabber
      process:
        directory: "/my/proj/diarybot"
        command: "/my/proj/diarybot/start"
      tags: ['diary']
        
    - role: site
      site_name: 'search'
      path: "/search/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "9096"
      process:
        directory: "/my/proj/search"
        command: "java -jar /my/proj/search/target/search-assembly-1.7.jar 9096"
        stdout_logfile_backups: 2
        stderr_logfile_backups: 2

    - role: site
      site_name: 'searchFiles'
      path: "/search/files/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "9089"
      process:
        directory: "/my/proj/fsindex"
        command: "/my/proj/fsindex/bin/python fsindex.py"

    - role: site
      site_name: 'whopickedthis'
      tags: ['whopickedthis']
      path: "/"
      openid: "anonymous"
      serverHost: "bang"
      internalPort: "9109"
      domain: "whopickedthis.com"
      useWebsocketPath: "yes"
      process:
        directory: "/my/site/whopickedthis"
        command: "/my/site/whopickedthis/whopickedthis.py"
        
    - role: site
      name: 'qrnotifyme'
      path: "/qrnotifyme/"
      openid: "anonymous"
      serverHost: "bang"
      internalPort: "9107"
      process:
        directory: "/my/proj/qrnotifyme"
        command: "/my/proj/qrnotifyme/bin/python qrnotifyme.py"

    - role: site
      site_name: 'gasuse'
      path: '/gasuse/'
      openid: 'anonymous'
      serverHost: 'bang'
      internalPort: '8081'
      process:
        directory: /my/proj/gasuse
        command: "/my/proj/gasuse/bin/python serve"
        user: drewp

    - role: site
      site_name: 'heist_querytransactions'
      path: "/heist/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "10003"
      process:
        directory: "/my/proj/heist"
        command: "/my/proj/heist/bin/python querytransactions.py"

    - role: site
      site_name: 'jessicaanddavidswedding'
      path: "/jessicaanddavidswedding/"
      openid: "no"
      serverHost: "bang"
      internalPort: "3190"
      process:
        directory: "/home/dmcc/wedding"
        command: "/home/dmcc/wedding/env/bin/python server_http.py"
      tags: ['jessicaanddavidswedding']

    - role: site
      site_name: 'firedata'
      path: "/firedata/"
      openid: "no"
      serverHost: "bang"
      internalPort: "3191"
      root_page_timeout_secs: 5
      process:
        directory: "/my/proj/firedata"
        command: "/usr/bin/coffee firedata.coffee"
      tags: ['firedata']
      
    - role: site
      site_name: 'firedata_zipborders'
      path: '/firedata/zipborders/'
      serverHost: "bang"
      internalPort: "3192"
      process:
        directory: "/my/proj/firedata"
        command: "/usr/bin/coffee zipborders.coffee"
      tags: ['firedata']

    - role: site
      site_name: 'colorcast'
      path: '/colorcast/'
      serverHost: "bang"
      internalPort: "9094"
      process:
        directory: "/my/proj/colorcast"
        command: "/my/proj/colorcast/bin/python getcolors.py"
      openid: "anonymous"

    - role: site
      site_name: 'daily'
      path: '/daily/'
      serverHost: "bang"
      internalPort: "9111"
      process:
        directory: "/my/proj/pimscreen/daily"
        command: "/my/proj/pimscreen/bin/python daily.py"
      openid: "admin"
      tags: ['daily']

    - role: site
      name: 'timebank'
      path: "/timebank/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "10006"
      process:
        directory: "/my/proj/ariRoom"
        command: "/my/proj/ariRoom/bin/python timebank.py"
      tags: ['timebank']
        
    - role: site
      site_name: 'dhcpleases'
      path: "/dhcpleases/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "9073"
      process:
        directory: "/my/proj/homeauto/service/dhcpleases/"
        command: "/my/proj/homeauto/service/dhcpleases/bin/python dhcpleases.py"
      tags: ['dhcpleases']

    - role: site
      site_name: 'wifi'
      path: "/wifi/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "9070"
      process:
        directory: "/my/proj/homeauto/service/tomatoWifi/"
        command: "/my/proj/homeauto/service/tomatoWifi/bin/python tomatoWifi.py"
      tags: ['wifi']

    - role: site
      site_name: 'beacon'
      path: "/beacon/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "9113"
      process:
        directory: "/my/proj/homeauto/service/beacon/"
        command: "/my/proj/homeauto/service/beacon/bin/python beaconmap.py"
      tags: ['beacon']

    - role: site
      site_name: 'colplay'
      path: "/colplay/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "9051"
      process:
        directory: "/my/proj/homeauto/service/colplay/"
        command: "/my/proj/homeauto/service/colplay/bin/python colplay.py"
      tags: ['colplay']

    - role: site
      name: 'sse_collector'
      path: "/sse_collector/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "9072"
      process:
        directory: "/my/proj/homeauto/service/reasoning/"
        command: "/my/proj/homeauto/service/reasoning/bin/python sse_collector.py"
      tags: ['reasoning']
      
    - role: site
      name: 'magma'
      path: "/magma/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "8010"
      process:
        directory: "/my/site/magma/"
        command: "/my/site/magma/env/bin/python serve_magma.py"
      tags: ['magma']
      
    - role: site
      site_name: 'arduinoNodeBang'
      path: "/arduino/bang/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "9059"
      useWebsocketPath: "yes"
      process:
        directory: "/my/proj/homeauto/service/arduinoNode/"
        command: "/my/proj/homeauto/service/arduinoNode/bin/python arduinoNode.py"
      tags: ['arduinoNode']

    - role: site
      site_name: 'gcalendarwatch'
      path: "/gcalendarwatch/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "9105"
      process:
        environment: "HOME=/home/drewp"
        directory: "/my/proj/pimscreen"
        command: "/my/proj/pimscreen/bin/python gcalendarwatch"
      tags: ['gcalendarwatch']

    - role: site
      site_name: 'grafana'
      path: "/grafana/"
      openid: "admin"
      serverHost: "bang"
      internalPort: "9067"
      process:
        user: root
        command: "docker run --rm --name grafana --net=host -p 9067:9067 -v /opt/grafana:/opt/grafana bang6:5000/grafana_x86:latest"
      tags: ['grafana']

- hosts: brace
  gather_facts: no
  handlers:
    - include: handlers/main.yml
  tasks:
    # for arduinonode
    - apt: pkg=arduino-mk
    - apt: pkg=indent
  roles:
    - role: site
      name: 'arduinoNodeBrace'
      path: "/arduino/brace/"
      openid: "admin"
      serverHost: "brace"
      internalPort: "9059"
      useWebsocketPath: "yes"
      process:
        directory: "/my/proj/homeauto/service/arduinoNode/"
        command: "/my/proj/homeauto/service/arduinoNode/bin/python arduinoNode.py"
      tags: ['arduinoNode']

- hosts: slash
  gather_facts: no
  handlers:
    - include: handlers/main.yml
  roles:
    - role: site
      name: 'arduinoNodeSlash'
      path: "/arduino/slash/"
      openid: "admin"
      serverHost: "slash"
      internalPort: "9059"
      useWebsocketPath: "yes"
      process:
        directory: "/my/proj/homeauto/service/arduinoNode/"
        command: "/my/proj/homeauto/service/arduinoNode/bin/python arduinoNode.py"
      tags: ['arduinoNode']
