---
- set_fact: job=supdebug port=10004 image_tag="latest"
- set_fact: base_image_platform="{{'pi' if ansible_architecture=='armv7l' else 'x86'}}"
- set_fact: image=bang6:5000/{{job}}_{{base_image_platform}}:{{image_tag}}
- docker_image: name={{image}} force=yes

- supervisor_process_mod:
    name="{{job}}_{{port}}"
    command="docker run --rm --name {{job}} -v /etc/passwd:/etc/passwd -v /etc/supervisord.conf:/etc/supervisord.conf -v /var/lib/supervisor.d:/var/lib/supervisor.d -v /tmp:/tmp -p {{port}}:{{port}} --net=host {{image}}"
    user=drewp
  notify: supervisord update

- template:
    dest=/var/lib/openid_proxy.d/supdebug_{{ansible_hostname}}.n3
    src=openid_proxy_statements.n3.j2
  notify: openid_proxy restart    
  delegate_to: bang
