---
- file: state=directory path=/opt/supdebug
- file: state=directory path=/opt/supdebug_env

# for later when this is in its own repo
#- name: initial checkout
#  command: darcs get ... creates=/opt/supdebug/_darcs
#- name: update
#  command: darcs pull ...

- synchronize: src=/my/proj/supdebug/ dest=/opt/supdebug archive=yes delete=yes 

- apt: pkg=python-virtualenv state=installed
- apt: pkg=python2.7-dev state=installed
- apt: pkg=libffi-dev state=installed
- apt: pkg=libssl-dev state=installed

- command: virtualenv --system-site-packages /opt/supdebug_env creates=/opt/supdebug_env/bin
- command: /opt/supdebug_env/bin/pip install -U pip

- apt: pkg=build-essential

- command: /opt/supdebug_env/bin/pip install cyclone tailer

- supervisor_process_mod:
    name=supdebug_10004
    directory=/opt/supdebug
    command="/opt/supdebug_env/bin/python supdebug.py"
    user=drewp
    autostart=true
  notify: supervisord update

- template:
    dest=/var/lib/openid_proxy.d/supdebug_{{ansible_hostname}}.n3
    src=openid_proxy_statements.n3.j2
  notify: openid_proxy restart    
  delegate_to: bang
