---
# haven't been moved to websites.yml yet


- supervisor_process_mod:
    name=picinput_11008
    directory=/my/proj/ffg
    command=/my/proj/ffg/bin/picInput
    user=drewp
  notify: supervisord update
  tags: ['picinput']

- supervisor_process_mod: 
    name=gasuse_8081
    directory=/my/proj/gasuse
    command="/my/proj/gasuse/bin/python /usr/bin/twistd -noy serve"
    user=drewp
  notify: supervisord update
    
- supervisor_process_mod: 
    name=semfile_8005
    directory=/my/proj/semfile
    command="/my/site/homepage/bin/python /usr/bin/twistd -noy serve"
    user=drewp
  notify: supervisord update
    
- supervisor_process_mod: 
    name=leafupdate_9058
    directory=/my/proj/leaf
    command="/my/proj/leaf/bin/python leafupdate.py"
    user=drewp
    autostart=true
  notify: supervisord update

- supervisor_process_mod: 
    name=recentPostFiles_9006
    directory=/my/site/homepage
    command=/my/site/homepage/recentPostFiles
    user=drewp
    autostart=true
  notify: supervisord update

- supervisor_process_mod: 
    name=recentReviews_9007
    directory=/my/site/homepage
    command=/my/site/homepage/recentReviews
    user=drewp
    autostart=true
  notify: supervisord update

- supervisor_process_mod: 
    name=twitterFavorites_9106
    directory=/my/site/homepage
    command=/my/site/homepage/twitterFavorites
    user=drewp
    autostart=true
  notify: supervisord update

- supervisor_process_mod: 
    name=newsbruiser_9008
    directory=/my/site/blog
    command=/my/site/blog/serve_blog
    user=newsbru
    autostart=true
  notify: supervisord update

- supervisor_process_mod: 
    name=adkins_9021
    command="thttpd -p 9021 -d /my/site/adkinslawgroup/cgi -c * -D -l /tmp/adkins-thttpd.log -nos"
    user=drewp
  notify: supervisord update

- supervisor_process_mod: 
    name=sfd_9024
    directory=/my/proj/sfd
    command="/my/proj/sfd/bin/python /my/proj/sfd/sfd.py"
    user=drewp
  notify: supervisord update

- supervisor_process_mod: 
    name=webcamserve_9047
    directory=/my/proj/webcam3
    user=drewp
    command="/my/proj/webcam3/bin/python webcamserve.py"
  notify: supervisord update
  tags: ['debug', 'webcamserve']

- supervisor_process_mod: 
    name=blaster_9052
    directory=/my/site/blog
    command="/my/site/blog/bin/spawning --port=9052 --processes=1 --threads=0 blaster.application"
    user=drewp
    stdout_logfile_backups=2
    stderr_logfile_backups=2
  notify: supervisord update

- supervisor_process_mod: 
    name=commentServe_9031
    directory=/my/proj/commentserve
    command="/my/proj/commentserve/bin/python commentServe.py"
    user=drewp
    stdout_logfile_backups=2
    stderr_logfile_backups=2
  notify: supervisord update

- supervisor_process_mod: 
    name=pimscreen_9035
    directory=/my/proj/pimscreen/pimscreen3
    command="/usr/bin/node pimscreen.js"
    user=drewp
    stdout_logfile_maxbytes=2MB
    stdout_logfile_backups=2
    stderr_logfile_maxbytes=2MB
    stderr_logfile_backups=2
  notify: supervisord update


- supervisor_process_mod: 
    name=countdown_10005
    directory=/my/proj/countdown
    command="/usr/sbin/thttpd -p 10005 -D"
    user=drewp
  notify: supervisord update
  tags: ['countdown']
  
- supervisor_process_mod: 
    name=webcam_snapshot_9057
    directory=/my/proj/httpsnapshot
    command="/my/proj/httpsnapshot/bin/spawning -p 9057 -s 1 -t 0 snapshot.application"
    user=drewp
  notify: supervisord update

- supervisor_process_mod: 
    name=netbars_3001
    directory=/tmp
    command="/usr/local/bin/netbars"
    user=root
  notify: supervisord update

- supervisor_process_mod: 
    name=computeracronym_9063
    directory=/my/site/computeracronym
    command="python2.7 ./acronymdecoder.py"
    user=drewp
  notify: supervisord update

- supervisor_process_mod: 
    name=envgraph_9075
    directory=/my/proj/homeauto/service/environment
    command="/my/proj/homeauto/service/environment/bin/python environment.py"
    user=drewp
  notify: supervisord update

- supervisor_process_mod: 
    name=shortener_9079
    directory=/my/site/shortener
    command="/usr/bin/python2.7 shortener.py 9079"
    user=drewp
  notify: supervisord update

- supervisor_process_mod: 
    name=timelinereview_9087
    directory=/my/site/timeline/timelinereview
    command="/my/site/timeline/timelinereview/bin/python timelinereview.py"
    user=drewp
  notify: supervisord update

- supervisor_process_mod: 
    name=gametag_3200
    user=drewp
    directory=/my/proj/gametag
    command="/usr/bin/make run_server"
  notify: supervisord update

- supervisor_process_mod:
    name=collabs_9065
    directory=/my/proj/collabs
    command="/my/proj/collabs/bin/python collabs.py"
    user=drewp
  notify: supervisord update
  tags: ['collabs']
    