---
# haven't been moved to websites.yml yet


- cron:
    user=root
    name="nginx_static_data"
    job="/bin/zsh -c '/my/proj/ansible/playbook -t nginx_static_data >&/dev/null'"
    special_time=hourly
  tags: ['nginx_static_data']

- supervisor_process_mod:
    name=picinput_11008
    directory=/my/proj/ffg
    command=/my/proj/ffg/bin/picInput
    user=drewp
  notify: supervisord update
  tags: ['picinput']
    
- apt: pkg=python-bottle
  tags: ['sites']
- apt: pkg=python-genshi
  tags: ['sites']
- supervisor_process_mod: 
    name=recentPostFiles_9006
    directory=/my/site/homepage
    command=/my/site/homepage/recentPostFiles
    user=drewp
    autostart=true
  notify: supervisord update
  tags: ['sites']

- supervisor_process_mod: 
    name=recentReviews_9007
    directory=/my/site/homepage
    command=/my/site/homepage/recentReviews
    user=drewp
    autostart=true
  notify: supervisord update
  tags: ['sites']

- supervisor_process_mod: 
    name=twitterFavorites_9106
    directory=/my/site/homepage
    command=/my/site/homepage/twitterFavorites
    user=drewp
    autostart=true
  notify: supervisord update
  tags: ['sites']

# for /my/site/blog/updateFeeds cron
- apt: pkg=python-librdf
  tags: ['sites', 'blog']
- supervisor_process_mod: 
    name=newsbruiser_9008
    directory=/my/site/blog
    command=/my/site/blog/serve_blog
    user=newsbru
    autostart=true
  notify: supervisord update
  tags: ['sites', 'blog']

- apt: pkg=mini-httpd
  tags: ['sites', 'adkins']
- supervisor_process_mod: 
    name=adkins_9021
    command="mini_httpd -p 9021 -d /my/site/adkinslawgroup/cgi -c * -D -l /tmp/adkins-thttpd.log"
    user=drewp
  notify: supervisord update
  tags: ['sites', 'adkins']

- supervisor_process_mod: 
    name=sfd_9024
    directory=/my/proj/sfd
    command="/my/proj/sfd/bin/python /my/proj/sfd/sfd.py"
    user=drewp
  notify: supervisord update
  tags: ['sites', 'sfd']

- supervisor_process_mod: 
    name=webcamserve_9047
    directory=/my/proj/webcam3
    user=drewp
    command="/my/proj/webcam3/bin/python webcamserve.py"
  notify: supervisord update
  tags: ['sites', 'webcamserve']

- supervisor_process_mod: 
    name=blaster_9052
    directory=/my/site/blog
    command="/my/site/blog/bin/spawning --port=9052 --processes=1 --threads=0 blaster.application"
    user=drewp
    stdout_logfile_backups=2
    stderr_logfile_backups=2
  notify: supervisord update
  tags: ['sites', 'blog']

- supervisor_process_mod: 
    name=commentServe_9031
    directory=/my/proj/commentserve
    command="/my/proj/commentserve/bin/python commentServe.py"
    user=drewp
    stdout_logfile_backups=2
    stderr_logfile_backups=2
  notify: supervisord update
  tags: ['sites']

- supervisor_process_mod: 
    name=pimscreen_9035
    directory=/my/proj/pimscreen/pimscreen3
    command="/usr/bin/nodejs pimscreen.js"
    user=drewp
    stdout_logfile_maxbytes=2MB
    stdout_logfile_backups=2
    stderr_logfile_maxbytes=2MB
    stderr_logfile_backups=2
  notify: supervisord update
  tags: ['sites', 'pim']


- apt: pkg=webfs
  tags: ['sites', 'countdown']
- supervisor_process_mod: 
    name=countdown_10005
    directory=/my/proj/countdown
    command="/usr/bin/webfsd -F -p 10005 -r /my/proj/countdown"
    user=drewp
  notify: supervisord update
  tags: ['sites', 'countdown']
  
- supervisor_process_mod: 
    name=webcam_snapshot_9057
    directory=/my/proj/httpsnapshot
    command="/my/proj/httpsnapshot/bin/python snapshot.py"
    user=drewp
  notify: supervisord update
  tags: ['sites']

# see netbars/setup.py
- apt: pkg=python-webpy
  tags: ['sites', 'netbars']
- apt: pkg=python-libpcap
  tags: ['sites', 'netbars']
- apt: pkg=python-docopt
  tags: ['sites', 'netbars']
- supervisor_process_mod: 
    name=netbars_3001
    directory=/my/proj/netbars
    command="/my/proj/netbars/install-env/bin/python install-env/bin/netbars --port 3001 --iface ens6 --local 10.1.10.10"
    user=root
  notify: supervisord update
  tags: ['sites', 'netbars']

- supervisor_process_mod: 
    name=computeracronym_9063
    directory=/my/site/computeracronym
    command="python2.7 ./acronymdecoder.py"
    user=drewp
  notify: supervisord update
  tags: ['sites']

- supervisor_process_mod: 
    name=envgraph_9075
    directory=/my/proj/homeauto/service/environment
    command="/my/proj/homeauto/service/environment/bin/python environment.py"
    user=drewp
  notify: supervisord update
  tags: ['sites']

- supervisor_process_mod: 
    name=timelinereview_9087
    directory=/my/site/timeline/timelinereview
    command="/my/site/timeline/timelinereview/bin/python timelinereview.py"
    user=drewp
  notify: supervisord update
  tags: ['sites']

- supervisor_process_mod: 
    name=gametag_3200
    user=drewp
    directory=/my/proj/gametag
    command="/usr/bin/make run_server"
  notify: supervisord update
  tags: ['sites']

- supervisor_process_mod:
    name=collabs_9065
    directory=/my/proj/collabs
    command="/my/proj/collabs/bin/python collabs.py"
    user=drewp
  notify: supervisord update
  tags: ['sites', 'collabs']
    
