---

- include: "../roles/nginx_forward/tasks/static_nginx_conf.yml"

- command: /my/proj/openid_proxy/bin/python build_nginx_conf.py /etc/nginx/nginx.conf bang chdir=/my/proj/openid_proxy
  notify: nginx restart
  tags: ['nginx', 'nginx_conf']
    
- supervisor_process_mod:
    name=nginx
    command="/usr/local/bin/pidproxy /var/log/nginx.pid /usr/sbin/nginx -c /etc/nginx/nginx.conf"
    user=root
    autostart=true
  notify: supervisord update
  tags: ['nginx']

- apt: pkg=tahoe-lafs
  tags: ['tahoe']
- supervisor_process_mod: 
    name=tahoe_home_8123
    directory=/opt/tahoe/home
    command="/usr/bin/tahoe run -C /opt/tahoe/home"
    user=drewp
    autostart=true
  notify: supervisord update
  tags: ['tahoe']

 
- supervisor_process_mod: 
    name=tahoe_home_introducer_54260
    command=/opt/tahoe/home-introducer/run
    user=drewp
    autostart=true
  notify: supervisord update
  tags: ['tahoe']

# unused
#- supervisor_process_mod: 
#    name=ffgDarcs_11009
#    directory=/my/proj/ffg/darcsweb
#    command=/my/proj/ffg/darcsweb/serve
#    user=drewp
#    autostart=true
#  notify: supervisord update

- supervisor_process_mod:
    name=powerEagleReader
    directory=/my/proj/homeauto/service/powerEagle
    command="/my/proj/homeauto/service/powerEagle/bin/python reader.py"
    user=drewp
    autostart=true
  notify: supervisord update
  tags: ['ha']

- supervisor_process_mod:
    name=whatsplayingnext_9110
    directory=/my/site/whatsplayingnext
    command="/my/site/whatsplayingnext/bin/python whatsplayingnext.py"
    user=drewp
    autostart=true
  notify: supervisord update
  tags: ['whatsplayingnext']

- cron: name=whatsplayingnext_update hour=3 minute=25 user=drewp job="/my/site/whatsplayingnext/scrape/update"
  tags: ['whatsplayingnext']
  
- supervisor_process_mod: 
    name=moinmoin_9011
    directory=/my/site/moin
    command=/my/site/moin/start
    user=drewp
    autostart=true
  notify: supervisord update
  tags: ['moin']

- supervisor_process_mod: 
    name=openid_proxy_9023
    directory=/my/proj/openid_proxy
    command="/my/proj/openid_proxy/bin/python /my/proj/openid_proxy/openid_proxy --port 9023"
    user=drewp
    stdout_logfile_backups=2
    stderr_logfile_backups=2
  notify: supervisord update
  tags: ['openid_proxy']

- supervisor_process_mod: 
    name=openid_proxy_nginx_9028
    directory=/my/proj/openid_proxy
    command="/my/proj/openid_proxy/openid_proxy_nginx"
    user=drewp
  notify: supervisord update
  tags: ['openid_proxy']

- supervisor_process_mod: 
    name=pim_twitterwatch
    directory=/my/proj/pimscreen
    command="/my/proj/pimscreen/bin/python twitterwatch"
    user=drewp
  notify: supervisord update
  tags: ['pim']

- supervisor_process_mod: 
    name=pim_deliciouswatch
    directory=/my/proj/pimscreen
    command="/my/proj/pimscreen/bin/python deliciouswatch"
    user=drewp
  notify: supervisord update
  tags: ['pim']

# for wedding-john-karin
- supervisor_process_mod: 
    name=zope4
    command="/bin/zsh /my/site/zope4/bin/runzope"
    user=drewp
  notify: supervisord update
  tags: ['zope']


# for harlan photos, maybe more
- supervisor_process_mod: 
    name=zope6
    command="/bin/zsh /my/site/zope6/bin/runzope"
    user=drewp
  notify: supervisord update
  tags: ['zope']

- supervisor_process_mod: 
    name=ffg_trafficGen
    directory=/my/proj/ffg
    command=/my/proj/ffg/bin/trafficGen
    user=drewp
    stdout_logfile_backups=2
    stderr_logfile_backups=2
  notify: supervisord update
  tags: ['ffg']

# needs new cgi solution
#- supervisor_process_mod: 
#    name=squid_mgr_9050
#    directory=/usr/lib/cgi-bin
#    command="thttpd -p 9050 -c cachemgr.cgi -D"
#    user=drewp
#  notify: supervisord update

- supervisor_process_mod: 
    name=c3po_9040
    directory=/my/proj/c3po
    command="/my/proj/c3po/env/bin/python c3po"
    user=drewp
  notify: supervisord update
  tags: ['pim']

- supervisor_process_mod: 
    name=cmd_photoBuildCache
    directory=/my/site/photo
    command="/usr/bin/python2.7 buildCache.py"
    user=drewp
    autostart=false
    autorestart=false
  notify: supervisord update
  tags: ['cmd']

- supervisor_process_mod: 
    name=cmd_backupDrewNote
    directory=/tmp
    command="/my/pda/drew-note/runbackup"
    user=drewp
    autostart=false
    autorestart=false
  notify: supervisord update
  tags: ['cmd']

- supervisor_process_mod: 
    name=cmd_seenlists
    directory=/home/drewp/mailprocess
    command="/usr/local/bin/python seennewlists"
    user=drewp
    autostart=false
    autorestart=false
    startsecs=0
    exitcodes=0
  notify: supervisord update
  tags: ['cmd']

- supervisor_process_mod: 
    name=cmd_trainnewspam
    directory=/home/drewp/mailprocess
    command="/usr/bin/zsh trainnewspam"
    user=drewp
    autostart=false
    autorestart=false
  notify: supervisord update
  tags: ['cmd']

- supervisor_process_mod: 
    name=pim_netbars2graphite
    directory=/tmp
    command="/my/proj/netbars/install-env/bin/python /my/proj/netbars/install-env/bin/netbars2graphite"
    user=drewp
    autorestart=true
  notify: supervisord update
  tags: ['pim']

- supervisor_process_mod: 
    name=pim_maildirwatch
    directory=/my/proj/pimscreen
    command="ionice -c 3 /my/proj/pimscreen/bin/python ./maildirwatch"
    user=drewp
    
  notify: supervisord update
  tags: ['pim']

- supervisor_process_mod: 
    name=openid_recentvisitors_9068
    directory=/my/proj/openid_proxy
    command="/my/proj/openid_proxy/bin/python recentvisitors.py 9068"
    user=drewp
  notify: supervisord update
  tags: ['pim']

- supervisor_process_mod: 
    name=csigen_9064
    directory=/my/proj/csigen
    command="/my/proj/csigen/bin/python csigen.py"
    user=drewp
  notify: supervisord update
  tags: ['csigen']
  
- supervisor_process_mod: 
    name=csigen_worker
    directory=/my/proj/csigen
    command="/my/proj/csigen/runworker"
    user=drewp
  notify: supervisord update
  tags: ['csigen']

- supervisor_process_mod: 
    name=reasoning_9071
    directory=/my/proj/homeauto/service/reasoning
    command="/my/proj/homeauto/service/reasoning/bin/python reasoning.py"
    user=drewp
    stdout_logfile_backups=2
    stderr_logfile_backups=2
  notify: supervisord update
  tags: ['ha']

- supervisor_process_mod: 
    name=pim_newlist_summary_9090
    directory=/home/drewp/mailprocess
    command="/home/drewp/mailprocess/bin/python newlist-summary"
    user=drewp
  notify: supervisord update
  tags: ['pim']

- supervisor_process_mod: 
    name=messagerule_9097
    directory=/home/drewp/mailprocess
    command="/home/drewp/mailprocess/bin/python messagerule.py"
    user=drewp
  notify: supervisord update
  tags: ['ha']

- supervisor_process_mod: 
    name=wallscreen_9102
    user=drewp
    directory=/my/proj/homeauto/service/wallscreen
    command="/my/proj/homeauto/service/wallscreen/bin/python wallscreen.py "
  notify: supervisord update
  tags: ['ha']

- supervisor_process_mod:
    name=pim_vist2rdf
    directory=/my/proj/pimscreen
    command="/my/proj/pimscreen/bin/python vist2rdf.py"
    user=drewp
  notify: supervisord update
  tags: ['pim']

- apt: pkg=ruby
  tags: ['reposync']
- cron: name="reposync" user="drewp" minute="0" hour="2" job="(cd /my/proj/reposync; ./quietsync)"
  tags: ['reposync']

