---
- name: No distro version of supervisor
  apt: name=supervisor state=absent
- apt: name=python-setuptools

- apt: name=python-pip

# see https://pypi.python.org/pypi/supervisor for changelog
# Holding at 3.1.3 because of https://github.com/Supervisor/supervisor/issues/807
# which is not yet fixed in 3.3.1.
- pip: name=supervisor version=3.1.3
- name: we will read config fragments from /var/lib/supervisor.d
  file: path=/var/lib/supervisor.d state=directory
- copy: dest=/etc/supervisord.conf src=supervisord.conf

- template: dest=/etc/systemd/system/supervisor@supervisord.service src=supervisor.service.j2
- template: dest=/etc/systemd/system/supervisor@supervisord-local.service src=supervisor.service.j2
  when: ansible_hostname == 'bang'
- command: systemctl enable /etc/systemd/system/supervisor@supervisord.service
  # sticker needs an upgrade to get systemctl
  when: ansible_hostname != 'sticker'
- command: systemctl enable /etc/systemd/system/supervisor@supervisord-local.service
  when: ansible_hostname == 'bang'
  