---

- set_fact: job=cjdns image_tag="latest"
  name: "cjdns top"
- set_fact: base_image_platform="{{'pi' if ansible_architecture=='armv7l' else 'x86'}}"
# hard to use bang6 here upon 1st setup. Need an simpler access to the repo.
- set_fact: image=bang:5000/{{job}}_{{base_image_platform}}:{{image_tag}}
- set_fact: image=bang6:5000/{{job}}_{{base_image_platform}}:{{image_tag}}
- docker_image: name={{image}} force=yes


- file: path=/opt/cjdns state=directory

- name: make config
  local_action: command python /my/proj/ansible/roles/cjdns/make_config.py "{{ inventory_hostname }}"
  register: cjdroute_conf
  tags: ['cjdns_config']

- name: install config
  copy: dest=/opt/cjdns/cjdroute.conf content="{{ cjdroute_conf.stdout }}" mode=0400
  tags: ['cjdns_config']
  
- name: make admin config
  local_action: shell python /my/proj/ansible/roles/cjdns/make_admin_config.py "{{ inventory_hostname }}"
  register: cjdnsadmin

- set_fact: adminUser=drewp

- name: install admin config
  copy: dest="/home/{{ adminUser }}/.cjdnsadmin"  content="{{ cjdnsadmin.stdout }}" mode=0400 owner="{{ adminUser }}"
  when: inventory_hostname != "drewnote"


- supervisor_process_mod:
    name={{job}}
    command="docker run --rm --name {{job}} -v /opt/cjdns/cjdroute.conf:/opt/cjdns/cjdroute.conf --network=host --cap-add=NET_ADMIN --device=/dev/net/tun {{image}} /bin/sh /opt/cjdns/run"
    directory=/opt/cjdns
    user=root
    stopasgroup=true
  notify: supervisord update
  
  
# write some /etc/hosts

# to look at the log, /opt/cjdns/contrib/python/cjdnslog DEBUG
