---
- set_fact: job=assistant image_tag="latest"
- set_fact: base_image_platform="{{'pi' if ansible_architecture=='armv7l' else 'x86'}}"
- set_fact: image=bang6:5000/{{job}}_{{base_image_platform}}:{{image_tag}}
- docker_image: name={{image}} force=yes

- supervisor_process_mod:
    name="{{job}}"
    command="docker run --rm --name {{job}} --net=host --mount type=bind,source=/tmp/pulseaudio,target=/tmp/pulseaudio {{image}}"
    user=drewp
  notify: supervisord update
