---


- name: container
  docker_container:
    name: mongo
    image: mongo:4.2.6-bionic
    volumes:
      - /opt/mongo-data:/data/db
    auto_remove: yes
    cleanup: yes
    published_ports: 27017:27017
    networks:
      - name: prometheus_on_bang
    command:
      - --bind_ip_all
      - --ipv6
      - --wiredTigerCacheSizeGB 1
