---
- set_fact: job=beacon image_tag="latest"
- set_fact: base_image_platform="{{'pi' if ansible_architecture=='armv7l' else 'x86'}}"
- set_fact: image=bang6:5000/{{job}}_{{base_image_platform}}:{{image_tag}}
- docker_image: name={{image}} force=yes

# clean up old ones for while
- file:  path=/opt/beacon_env state=absent

- set_fact: bang_addr="bang.vpn-home.bigasterisk.com"

- supervisor_process_mod:
    name=rssiscan
    user=root
    command="docker run --name rssiscan --rm --net=host {{image}} python rssiscan.py {{bang_addr}} {{ansible_hostname}}"
  notify:
    - supervisord update
  
