---
  
- hostname: name={{inventory_hostname}}
- timezone: name="America/Los_Angeles"

- apt: pkg=dirmngr
- set_fact: rel=stretch
- set_fact: rel=buster
  when: inventory_hostname in ['frontdoor2','kitchen']
  
- copy: content="deb http://mirrordirector.raspbian.org/raspbian/ {{rel}} main contrib non-free rpi\ndeb http://security.debian.org/ {{rel}}/updates main contrib non-free rpi\ndeb http://archive.raspberrypi.org/debian {{rel}} main" dest=/etc/apt/sources.list
- apt_key: url=https://ftp-master.debian.org/keys/archive-key-8.asc
- apt_key: url=https://ftp-master.debian.org/keys/archive-key-8-security.asc
- apt_key: url=https://ftp-master.debian.org/keys/archive-key-9-security.asc
- apt_key: keyserver=keyserver.ubuntu.com id=8B48AD6246925553
- file: path=/etc/apt/sources.list.d/raspi.list state=absent
- apt: pkg=debian-keyring
  name: deb keyring
  when: inventory_hostname not in ['frontdoor2','kitchen']
- apt: pkg=debian-archive-keyring
  name: deb archive keyring
  when: inventory_hostname not in ['frontdoor2','kitchen']
- apt: pkg=apt-utils

  
#- copy: dest="/etc/network/interfaces.d/wlan1" content="auto wlx0087341d93e7\n iface wlx0087341d93e7 inet dhcp\n  post-up iw wlx0087341d93e7 set power_save off\n auto wlan0\n iface wlan0 inet manual\n post-up /sbin/ifdown wlan0\n "
#  when: ansible_hostname == "frontdoor"
  
- copy: dest="/etc/network/interfaces.d/wlan0" content="auto wlan0\niface wlan0 inet dhcp\n  post-up iw wlan0 set power_save off\n"
  name: wlan0 powersave
  when: inventory_hostname in ["frontdoor", "living"]
- command: "iw wlan0 set power_save off"
  name: wlan0 powersave now
  when: inventory_hostname in ["frontdoor", "living"]


# this may be leading to broken wifi
#- apt: update_cache=yes upgrade=dist
#  name: apt upgrade
# may need reboot here for kernel.

- apt: pkg=build-essential 
  name: "apt build-essential"
- apt: pkg=libffi-dev update_cache=yes
  name: "apt libffi and update for some reason"
  when: inventory_hostname not in ['frontdoor2','kitchen']
- apt: pkg=libpython2.7-dev  
  when: inventory_hostname not in ['frontdoor2','kitchen']
- apt: pkg=libssl-dev  
  when: inventory_hostname not in ['frontdoor2','kitchen']
- apt: pkg=python-pip
  name: "python-pip"
- apt: pkg=python-setuptools update_cache=yes
- apt: pkg=python-virtualenv
- apt: pkg=python-docker
- apt: pkg=rsync  
- apt: pkg=i2c-tools
- apt: pkg=sysstat

# still needed? was part of supdebug.
# https://github.com/graphite-project/graphite-web/issues/1721
- apt: pkg=python-openssl state=absent


# stop SD card corruption
- apt: pkg=dphys-swapfile state=absent
  name: reduce sd writes
- mount: path=/var/log src=tmpfs fstype=tmpfs state=present opts=defaults,noatime,mode=0755
- mount: path=/tmp src=tmpfs fstype=tmpfs state=present opts=defaults,noatime
    

#  /boot/config.txt could have gpu_mem=16

# for beacon
#enable_uart=1
#dtoverlay=pi3-miniuart-bt
#core_freq=250

# for tiny_screen
- lineinfile: dest=/boot/config.txt line="dtparam=spi=on" regexp="^dtparam=spi="

# downgrade strictness so I can install from https://archive.raspberrypi.org/
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907788
- lineinfile: dest=/etc/ssl/openssl.cnf line="#CipherString = DEFAULT@SECLEVEL=2" regexp="CipherString ?="
