---
  
- hostname: name={{inventory_hostname}}
- timezone: name="America/Los_Angeles"

- apt: pkg=dirmngr
  name: dirmngr
- set_fact: rel=buster
  
- copy: content="deb http://mirrordirector.raspbian.org/raspbian/ {{rel}} main contrib non-free rpi\ndeb http://security.debian.org/ {{rel}}/updates main contrib non-free rpi\ndeb http://archive.raspberrypi.org/debian {{rel}} main" dest=/etc/apt/sources.list
- apt_key: url=https://ftp-master.debian.org/keys/archive-key-8.asc
- apt_key: url=https://ftp-master.debian.org/keys/archive-key-8-security.asc
- apt_key: url=https://ftp-master.debian.org/keys/archive-key-9-security.asc
- apt_key: keyserver=keyserver.ubuntu.com id=8B48AD6246925553
  when: ansible_distribution != "Debian"
- file: path=/etc/apt/sources.list.d/raspi.list state=absent
- apt: pkg=apt-utils

# plus this, for chromium?
#deb http://security.debian.org/debian-security buster/updates main 

#- copy: dest="/etc/network/interfaces.d/wlan1" content="auto wlx0087341d93e7\n iface wlx0087341d93e7 inet dhcp\n  post-up iw wlx0087341d93e7 set power_save off\n auto wlan0\n iface wlan0 inet manual\n post-up /sbin/ifdown wlan0\n "
#  when: ansible_hostname == "frontdoor"
  
- copy: dest="/etc/network/interfaces.d/wlan0" content="auto wlan0\niface wlan0 inet dhcp\n  post-up iw wlan0 set power_save off\n"
  name: wlan0 powersave
  when: inventory_hostname in ["frontdoor", "living"]
- command: "iw wlan0 set power_save off"
  name: wlan0 powersave now
  when: inventory_hostname in ["frontdoor", "living"]


# this may be leading to broken wifi
#- apt: update_cache=yes upgrade=dist
#  name: apt upgrade
# may need reboot here for kernel.

- apt: pkg=build-essential update_cache=yes
  name: "apt build-essential"
  tags: ['apt_update']
#- apt: pkg=libffi-dev 
- apt:
    pkg:
      - python-pip
      - python-setuptools
      - python-virtualenv
      - python-docker
      - python3-docker
      - rsync  
      - i2c-tools
      - sysstat

# still needed? was part of supdebug.
# https://github.com/graphite-project/graphite-web/issues/1721
- apt: pkg=python-openssl state=absent
  name: no python-openssl

# stop SD card corruption
- apt: pkg=dphys-swapfile state=absent
  name: reduce sd writes
- mount: path=/var/log src=tmpfs fstype=tmpfs state=present opts=defaults,noatime,mode=0755
  name: /var/log to tmpfs
- mount: path=/tmp src=tmpfs fstype=tmpfs state=present opts=defaults,noatime
  name: /tmp to tmpfs
    

#  /boot/config.txt could have gpu_mem=16

# for beacon
#enable_uart=1
#dtoverlay=pi3-miniuart-bt
#core_freq=250

# for tiny_screen
- lineinfile: dest=/boot/config.txt line="dtparam=spi=on" regexp="^dtparam=spi="

# downgrade strictness so I can install from https://archive.raspberrypi.org/
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907788
- lineinfile: dest=/etc/ssl/openssl.cnf line="#CipherString = DEFAULT@SECLEVEL=2" regexp="CipherString ?="
