---
- name: supervisord update
  # this one might also be where I remove old files that weren't
  # changed in the last update, somehow. Maybe write them all with a
  # timestamp for this ansible run and then remove everything older?
  #
  # also, supervisor might not be running, and then this probably
  # *shouldn't* error since an update will happen when supervisor
  # next starts
  shell: "/usr/local/bin/supervisorctl update || true"
 
- name: nginx update
  command: "/usr/local/bin/supervisorctl restart nginx"

- name: nginx restart
  command: "/usr/local/bin/supervisorctl restart nginx"

- name: house dns restart
  command: "/usr/local/bin/supervisorctl -c /etc/supervisord-local.conf restart tinydns"
  
- name: wifi net reset
  shell: "/sbin/ifdown ens5; /sbin/ifup ens5"

- name: firewall setup
  command: /bin/sh /etc/network/firewall-setup

- name: openid_proxy restart
  command: "/usr/local/bin/supervisorctl restart openid_proxy_9023"

- name: reload telegraf
  command: "/usr/local/bin/supervisorctl restart telegraf"

- name: sshd restart
  service: name=ssh enabled=yes state=reloaded

- name: openvpn restart
  service: name=openvpn enabled=yes state=reloaded

- name: cups restart
  service: name=cups enabled=yes state=reloaded

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart docker
  service: name=docker state=restarted


