---

- apt: pkg=lightdm state=absent
- apt: pkg=slim

- copy: dest=/etc/slim.conf src=slim.conf

# /etc/init/pulseaudio.conf enable line with: start on

- supervisor_process_mod:
    name=pulseaudio
    directory=/tmp
    environment="DISPLAY=:0,XAUTHORITY=/home/drewp/.Xauthority"
    command="pulseaudio"
    user=drewp
  notify: supervisord update

- supervisor_process_mod:
    name=room_server_10005
    directory=/my/proj/ariRoom
    command="/my/proj/ariRoom/bin/python ariRoom.py"
    user=drewp
  notify: supervisord update
  
- supervisor_process_mod:
    name=display_console
    environment="DISPLAY=:0,XAUTHORITY=/home/drewp/.Xauthority"
    command="/usr/bin/google-chrome-unstable --app=https://bigasterisk.com/room/ari/"
    directory="/home/drewp"
    user=drewp
    autostart=false
  notify: supervisord update

- supervisor_process_mod:
    name=display_minetest
    environment="DISPLAY=:0,XAUTHORITY=/home/drewp/.Xauthority"
    command="/home/drewp/start_minetest 30000"
    directory="/home/drewp"
    user=drewp
    autostart=false
    stopasgroup=true
  notify: supervisord update

- supervisor_process_mod:
    name=display_minetest_oakland
    environment="DISPLAY=:0,XAUTHORITY=/home/drewp/.Xauthority"
    command="/home/drewp/start_minetest 30001"
    directory="/home/drewp"
    user=drewp
    autostart=false
    stopasgroup=true
  notify: supervisord update

- supervisor_process_mod:
    name=display_minecraft
    environment="DISPLAY=:0,XAUTHORITY=/home/drewp/.Xauthority"
    command="/usr/bin/java -jar /home/drewp/Minecraft.jar"
    directory="/home/drewp"
    user=drewp
    autostart=false
    stopasgroup=true
  notify: supervisord update

- supervisor_process_mod:
    name=display_stopmotion
    environment="DISPLAY=:0,XAUTHORITY=/home/drewp/.Xauthority"
    command="/home/drewp/linuxstopmotion-code/build/stopmotion"
    directory="/home/drewp"
    user=drewp
    autostart=false
    stopasgroup=true
  notify: supervisord update

- supervisor_process_mod:
    name=display_blender
    environment="DISPLAY=:0,XAUTHORITY=/home/drewp/.Xauthority"
    command="/usr/bin/blender --window-borderless"
    directory="/home/drewp"
    user=drewp
    autostart=false
    stopasgroup=true
  notify: supervisord update


