---
- apt: pkg=python-gst0.10
- apt: pkg=gstreamer0.10-plugins-good

- name: webcam {{ camName }} serving on {{ internalPort }} with -c {{ config }}
  supervisor_process_mod:
    name=webcam_{{ camName }}_{{ internalPort }}
    directory=/my/proj/webcam2
    user=drewp
    autostart=true
    autorestart=true
    command="/my/proj/webcam2/{{ 'bin/python' if ansible_architecture == 'x86_64' else 'env32/bin/python' }} /my/proj/webcam2/gstgrab -c {{ config }}"
  notify: supervisord update
