---
- name: No distro version of supervisor
  apt: name=supervisor state=absent

- apt: name=python3-pip
  
# see https://pypi.python.org/pypi/supervisor for changelog
# Holding at 3.1.3 because of https://github.com/Supervisor/supervisor/issues/807
# which is not yet fixed in 3.3.1. LKG 3.1.3
- pip: name=supervisor version=4.1.0
- name: we will read config fragments from /var/lib/supervisor.d
  file: path=/var/lib/supervisor.d state=directory
- copy: dest=/etc/supervisord.conf src=supervisord.conf

- file: path=/etc/systemd/system/supervisord.service state=absent
- template: dest=/etc/systemd/system/supervisor@supervisord.service src=supervisor.service.j2
- template: dest=/etc/systemd/system/supervisor@supervisord-local.service src=supervisor.service.j2
  when: ansible_hostname == 'bang'
- service: name=supervisor@supervisord.service enabled=yes state=started
- service: name=supervisor@supervisord-local.service enabled=yes state=started
  when: ansible_hostname == 'bang'

  
