---

# was in supervisor; now the package comes with systemd service
- file: path=/var/lib/supervisor.d/pigpiod_8888.conf state=absent
  notify: supervisord update

- apt: pkg=pigpio
- service: name=pigpiod enabled=yes state=started