---
- file: state=directory path=/opt/piNode
# put this outside /opt/piNode since we rsync --delete in there.
- file: state=directory path=/opt/piNode_env
- file: state=directory path=/opt/arduinoNode
- file: state=directory path=/opt/homeauto_lib

- apt: pkg=build-essential
- apt: pkg=python-dev
- apt: pkg=libffi-dev
- apt: pkg=git
  
- synchronize:
    src=/my/proj/homeauto/service/piNode/
    dest=/opt/piNode
    archive=yes
    delete=yes


# may need to 'pip install -U setuptools' in here first
- pip:
    chdir=/opt/piNode_env
    requirements=/opt/piNode/requirements.txt
    virtualenv=/opt/piNode_env


- synchronize: src=/my/proj/homeauto/service/arduinoNode/ dest=/opt/arduinoNode archive=yes delete=yes
- synchronize: src=/my/proj/homeauto/lib/ dest=/opt/homeauto_lib archive=yes delete=yes
- copy: src=/my/site/magma/stategraph.py dest=/opt/homeauto_lib
- copy: src=/my/proj/room/carbondata.py dest=/opt/homeauto_lib
- synchronize: src=/my/proj/light9/light9 dest=/opt/homeauto_lib archive=yes
  
- lineinfile: dest=/etc/modules line="ipv6"

# using 1-wire? (piNode program knows if this is the case)
- lineinfile: dest=/boot/config.txt line="dtoverlay=w1-gpio,gpiopin=17,pullup=y"
  when: inventory_hostname in ["kitchen", "living", "garage"]


- supervisor_process_mod:
    name=piNode_9059
    directory=/opt/piNode
    autostart=true
    user=root
    startsecs=30
    command="/opt/piNode_env/bin/python piNode.py"
  notify: supervisord update

