---
- set_fact: job=pi_node port=9059 image_tag="latest"
- set_fact: base_image_platform="{{'pi' if ansible_architecture=='armv7l' else 'x86'}}"
- set_fact: image=bang6:5000/pinode_{{base_image_platform}}:{{image_tag}}
- docker_image: name={{image}} force=yes

- lineinfile: dest=/etc/modules line="ipv6"

# using 1-wire? (piNode program knows if this is the case)
- lineinfile: dest=/boot/config.txt line="dtoverlay=w1-gpio,gpiopin=17,pullup=y"
  when: inventory_hostname in ["frontbed", "kitchen", "living", "garage", "frontdoor", "workshop", "bed"]

- lineinfile: dest=/boot/config.txt line="dtparam=i2c_arm=on"
  when: inventory_hostname in ["frontdoor", "workshop"]

- lineinfile: dest=/etc/modules line="i2c-dev"
  when: inventory_hostname in ["frontdoor", "workshop"]

  
# pi 3 onboard audio conflicts with pwm used for ws2812 leds. https://github.com/jgarff/rpi_ws281x/wiki
- lineinfile: dest=/boot/config.txt line="dtparam=audio=off" regexp="^dtparam=audio="

# old name
- file: path=/var/lib/supervisor.d/piNode_9059.conf state=absent
  
- supervisor_process_mod:
    name="{{job}}_{{port}}"
    autostart=true
    user=root
    startsecs=30
    command="docker run --name {{job}} --rm -p {{port}}:{{port}} --uts=host --net=host --cap-add SYS_RAWIO --device /dev/mem  --privileged --memory=400m {{image}}"
  notify: supervisord update


- set_fact:
    name: "{{ansible_hostname}}_{{job}}"
    domain: "bigasterisk.com"
    path: "/pi/{{ansible_hostname}}/"
    upstreamTarget: "http://{{ansible_hostname}}.bigasterisk.com:{{port}}/"
    openid: admin
    useWebsocketPath: yes

- template:
    dest=/var/lib/openid_proxy.d/{{name}}.n3
    src=openid_proxy_statements.n3.j2
  notify: openid_proxy restart    
  delegate_to: bang
