---
- apt: name=djbdns state=present
- user: name=Gdnscache
- user: name=Gdnslog

- apt: name=dnscache-run state=present

- file: dest=/etc/dnscache/root/ip/192.168 state=absent
- copy: dest=/etc/dnscache/env/IP content="10.2.0.1"
- file: dest=/etc/dnscache/root/ip/10 state=touch
  
- name: send bigasterisk.com requests to local tinydns
  notify: house dns restart
  copy: dest=/etc/dnscache/root/servers/{{ item }} content="127.0.0.1"
  with_items:
    - bigasterisk.com
    - whatsplayingnext.com
    - whopickedthis.com
    - quickwitretort.com

- service: name=daemontools enabled=true state=restarted
    
# /etc/supervisord-local.conf needs this:
#[program:dnscache]
#directory=/etc/dnscache
#command=/etc/dnscache/run
#user=root
## log is very noisy and boring- led to lots of disk activity
#stdout_logfile=/dev/null
