#!/usr/bin/python
"""
compare to https://github.com/tomdc/graphite-zpool/blob/master/zpool_iostat.pl
"""
import subprocess, time, sys
pool = sys.argv[1]

def toBytes(s):
    if s[-1].isdigit():
       return float(s)
    unit = s[-1]
    val = float(s[:-1])
    return val * {'K': 1<<10,'M': 1<<20}[unit]

# the first output line is strangely low and doesn't update often. The next one looks good.
lines = subprocess.check_output(["/usr/bin/sudo", "/sbin/zpool", "iostat", pool, "1", "3"]).splitlines()
pool, alloc, free, readOps, writeOps, read, write = lines[-1].split()
now = int(time.time())
print "host.stor.%s.zpool.read_bytes %d %d" % (pool, toBytes(read), now)
print "host.stor.%s.zpool.write_bytes %d %d" % (pool, toBytes(write), now)
print "host.stor.%s.zpool.read_ops %s %d" % (pool, readOps, now)
print "host.stor.%s.zpool.write_ops %s %d" % (pool, writeOps, now)
