---


- cron: minute=5 hour=5 day=1 name="ssl cert renew" user="root" job="/my/proj/ansible/playbook  -t nginx_ssl_certs -l bang,prime"
  delegate_to: bang
  
- set_fact:
    site_with_certs:
      - adkinslawgroup.com
      - bigasterisk.com
      - drewp.quickwitretort.com
      - fantasyfamegame.com
      - iveseenyoubefore.com
      - kelsi.quickwitretort.com
      - maxradi.us
      - photo.bigasterisk.com
      - projects.bigasterisk.com
      - quickwitretort.com
      - whatsplayingnext.com
      - whopickedthis.com
      - williamperttula.com
      - brazilog.bigasterisk.com
      - cinepaint.bigasterisk.com
      - cuisine.bigasterisk.com
      - darcs.bigasterisk.com
      - gametag.bigasterisk.com
      - graphite.bigasterisk.com
      - karinandjohn.bigasterisk.com
      - light9.bigasterisk.com
      - lisa.bigasterisk.com
      - lisaanddave.bigasterisk.com
      - seabird.bigasterisk.com
      - stef.bigasterisk.com
      - wedding-john-karin.bigasterisk.com
      - wedding.bigasterisk.com
      - csigen.quickwitretort.com
      - dmcc.quickwitretort.com
      - bebop.bigasterisk.com
      - digibook.bigasterisk.com
      - linuxmovies.bigasterisk.com
      - computeracronym.quickwitretort.com
      - snappletronics.quickwitretort.com
      - johnmuir.bigasterisk.com

#- shell: /my/doc/ssl/combine_cert {{ item }} > /my/doc/ssl/build/{{ item }}-full.crt
#  delegate_to: bang
#  with_items: site_with_certs
#
#- file: path=/var/lib/nginx.d/ssl state=directory
#- copy: dest="/var/lib/nginx.d/ssl/bigasterisk-2012-nopassphrase-key.pem"
#    src="/my/doc/ssl/bigasterisk-2012-nopassphrase-key.pem"
#    owner=root
#    mode=0400
#- copy:
#    dest="/var/lib/nginx.d/ssl/{{ item }}-full.crt"
#    src="/my/doc/ssl/build/{{ item }}-full.crt"
#    owner=root
#    mode=0400
#  with_items: site_with_certs
#  notify: nginx restart

- command: zsh run chdir=/my/doc/ssl/letsencrypt
  become: true
  become_user: drewp
  delegate_to: bang

- synchronize: dest=/var/lib/nginx.d/ssl/site/ src=/my/doc/ssl/letsencrypt/site/ recursive=yes delete=yes
  notify: nginx restart
