---

- set_fact: openidProxyAddr="http://bang:9023"
  name: set openidProxyAddr
  tags: ['ruler-check']

- set_fact: upstreamTarget="http://{{serverHost}}.bigasterisk.com:{{internalPort}}{{upstreamPath}}"
  name: set upstreamTarget  
  tags: ['ruler-check']

- set_fact: upstreamTarget="http://[fc9d:ce7a:c40:7dac:439b:289c:dd2d:5101]:{{internalPort}}{{upstreamPath}}"
  name: set upstreamTarget to brace  
  when: serverHost == "brace"

- set_fact: proxyTarget="{{openidProxyAddr}}{{path}}"
  name: set proxyTarget   
  tags: ['ruler-check']
- set_fact: proxyTarget="{{upstreamTarget}}"
  name: set proxyTarget   
  when: openid == "no"
  tags: ['ruler-check']

- set_fact: nginxLocation="proxy_pass {{proxyTarget}}; "
  name: set nginxLocation  
  tags: ['ruler-check']
- debug: msg="accessLog={{ accessLog }} openid={{ openid }}"
  tags: ['ruler-check']
- set_fact: accessLogLine="{{'' if accessLog else 'access_log off; '}}"
  name: set accessLogLine
  tags: ['ruler-check']

- include: setup_directories.yml
  tags: ['ruler-check']

- file: path="/var/lib/nginx.d/{{domain}}/no-nfs/" state=directory
- copy:
    dest="/var/lib/nginx.d/{{domain}}/no-nfs/{{name}}.conf"
    content="location {{path}} { {{nginxLocation}} {{accessLogLine}} }"
    # always include the addslash redirect?
  notify: nginx restart
  delegate_to: bang

  # this might end up on another host

# note that user may be overridden by arg_dict sometimes
- supervisor_process_mod:
    name="{{ name }}_{{ internalPort }}"
    user=drewp
    arg_dict="{{process}}"
  notify: supervisord update

- template:
    dest=/var/lib/openid_proxy.d/{{name}}.n3
    src=openid_proxy_statements.n3.j2
  notify: openid_proxy restart    
  delegate_to: bang

  
#- template:
#    dest="/my/proj/puppet/ansible/roles/sensu_client/files/generated/site/{{name}}.json"
#    src=sensu-check.json.j2
#  # notify: (todo: all sensus on all machines)

- file: path=/var/lib/ruler.d/site state=directory
  delegate_to: bang

- template:
    dest="/var/lib/ruler.d/site/{{name}}.n3"
    src=ruler-check.n3.j2
  tags: ['ruler-check']
  delegate_to: bang

# maybe also a ruler check on the local host
