---

- apt: pkg=isc-dhcp-server

# from https://bugs.launchpad.net/ubuntu/+source/isc-dhcp/+bug/1186662/comments/25
# todo: /etc/fstab root needs option 'acl'
- command: setfacl -dm u:dhcpd:rwx /var/lib/dhcp
- command: setfacl -m u:dhcpd:rwx /var/lib/dhcp

- copy:
    dest=/etc/default/isc-dhcp-server
    content="# written by /my/proj/ansible/roles/network_bigasterisk_gateway{{'\n'}}INTERFACES=\"enp1s0 ens5\"{{'\n'}}"
    owner=root
    group=root
  notify: dhcpd reload
  
- copy:
    dest=/etc/dhcp/dhcpd.conf
    src=dhcpd.conf
    owner=root
    group=root
  notify: dhcpd reload
    
- service: name=isc-dhcp-server state=restarted
