---
- apt: name=djbdns state=present

- user: name=Gtinydns
- user: name=Gdnslog
  
- command: tinydns-conf Gtinydns Gdnslog /etc/tinydns 0.0.0.0 creates=/etc/tinydns

- copy: dest=/etc/tinydns/root/data src=tinydns_data owner="root" group="root"
  notify: tinydns data
# still missing many domains- should be generated

# /etc/supervisord-local.conf needs this:
#[program:tinydns]
#directory=/etc/tinydns
#command=/etc/tinydns/run
#user=root


- user: name=Gdnslog

  
#  still not answering the override answer for bigasterisk. maybe authority problem. maybe dnsmasq will just do it

#  write tests for the dns requests i want to see. add filtered view in ruler for these tests and a run-all-in-view button

# house-host rule that sends them to here. openvpn control?
