---

# /opt/atomojo-server-0.12.1 was hand-made

- supervisor_process_mod: 
    name=atomojo_9025
    directory=/opt/atomojo-server-0.12.1
    command="java -Xmx2048m -jar /opt/atomojo-server-0.12.1/atomojo-server.jar /my/site/blog/mojo"
    user=drewp
  notify: supervisord update

- supervisor_process_mod: 
    name=wp2atom_9026
    command="/my/site/blog/bin/python /my/site/blog/baby/wp2atom"
    user=drewp
  notify: supervisord update

- supervisor_process_mod: 
    name=blogrender_9027
    directory=/my/site/blog/baby
    command="/my/site/blog/bin/python blogrender.py"
    user=drewp
  notify: supervisord update
