#!/usr/bin/python

# <graphite prefix no trailing dot> <munin checker path> ...<more args to the check call>
import subprocess, time, sys


output = subprocess.check_output(sys.argv[2:]).splitlines()
now = time.time()
for line in output:
    k, v = line.strip().split()
    assert k.endswith('.value'), k
    k = k[:-len('.value')]
    print "%s.%s %s %d" % (sys.argv[1], k, v, now)
