---
- apt: pkg=unison
- file: owner=drewp path=/home/drewp/unison state=directory
- file: owner=drewp path=/home/drewp/.unison state=directory

# talking over cjdns is currently WAY slower, not sure why
- copy: owner=drewp dest=/home/drewp/.unison/home.prf content="root = /home/drewp/unison\nroot = ssh{{':'}}//bang//home/drewp/unison"
  when: inventory_hostname in ["slash", "dash"]
- copy: owner=drewp dest=/home/drewp/.unison/home.prf content="root = /home/drewp/unison\nroot = ssh{{':'}}//bang6//home/drewp/unison"
  when: inventory_hostname not in ["slash", "dash"]
  
- file: owner=drewp path=/home/drewp/bin state=directory
- copy: owner=drewp dest=/home/drewp/bin/u content="unison home -batch -terse" mode="u+rwx"

- file: force=yes owner=drewp dest=/home/drewp/.emacs.d state=link src=unison/dot-emacs-d
- file: force=yes owner=drewp dest=/home/drewp/.fonts state=link src=unison/dot-fonts
- file: force=yes owner=drewp dest=/home/drewp/.zshrc state=link src=unison/zshrc
- file: force=yes owner=drewp dest=/home/drewp/.i3 state=link src=unison/dot-i3

# don't share .aptitude/cache
- file: owner=drewp path=/home/drewp/.aptitude state=directory
- file: owner=drewp dest=/home/drewp/.aptitude/config state=link src=../unison/dot-aptitude-config force=yes
  
# zshrc uses these:
- apt: pkg=keychain
- apt: pkg=zsh-common


# not unison at all, just tools i want
- apt: pkg=spacefm-gtk3
- apt: pkg=gnome-icon-theme-full
- apt: pkg=atool

