---

# just leftover setup for this one kiosk. see raspi_kiosk_chrome/tasks/main.yml for the main steps.

# boot-to-x:
# Created symlink from /etc/systemd/system/default.target to /lib/systemd/system/graphical.target.

- apt: pkg=julia

- copy: src=/my/proj/raspberry_pi_kiosk/pir_screen.jl dest=/home/pi/

- copy: src=wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf

- supervisor_process_mod:
    name=pir_screen
    environment="DISPLAY=:0.0"
    directory=/home/pi
    command="/usr/bin/julia pir_screen.jl 4 60"
    user=pi
#  notify: supervisord update
