---

# from https://github.com/githubixx/ansible-role-wireguard

- name: Install required packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - software-properties-common
    - linux-headers-{{ ansible_kernel }}
  tags:
    - wg-install

- name: Add WireGuard repository
  apt_repository:
    repo: "ppa:wireguard/wireguard"
    state: present
    update_cache: yes
  tags:
    - wg-install

