---

# see tasks/bang_sites.yml for cron that runs this.

# this could just read all the :serveRoot paths from the site
# descriptions. And it's so slow, it should probably be a single
# custom tool.

- include: site_paths.yml

- name: prep dir for serving
  file: path="{{ item }}" state=directory
  with_items: site_paths
  
- name: sync
  synchronize: delete=yes archive=yes src="{{ item }}" dest="{{ item }}"
  with_items: site_paths

- name: leave rsync warning
  copy: dest="{{ item }}/RSYNC_DELETE_RUNS_IN_HERE" content="don't add files on this side!"
  with_items: site_paths

# for /usr/share/graphite-web/static
- apt: name=graphite-web
  tags: ['graphite']
- file: path=/var/lib/graphite/whisper state=directory owner=_graphite group=_graphite
  tags: ['graphite']
