---
- group: gid=14564 name=dropbox
- user: name=dropbox uid=14564 group=dropbox

- file: path=/etc/apt/sources.list.d/dropbox.list state=absent
- get_url:
    dest=/home/dropbox/dropbox-lnx.x86_64.tgz
    url=https://www.dropbox.com/download?plat=lnx.x86_64
- file: path=/home/dropbox/.dropbox-dist state=absent
- unarchive: src=/home/dropbox/dropbox-lnx.x86_64.tgz dest=/home/dropbox
- file: path=/home/dropbox/.dropbox-dist state=directory recurse=yes owner=dropbox

- file: path=/home/dropbox/Dropbox state=directory owner=dropbox group=drewp mode=0750
  
# This works in /home/dropbox/.dropbox and /home/dropbox/Dropbox
- supervisor_process_mod: 
    name=dropbox
    environment="HOME=/home/dropbox"
    command="/home/dropbox/.dropbox-dist/dropbox-lnx.x86_64-3.12.6/dropbox"
    user=dropbox
    stopasgroup=true
  notify: supervisord update

# to check DB status, set HOME=/home/dropbox then
# python ~drewp/bin/dropbox.py status
# to learn if it's syncing or whatever
