---
- group: gid=14564 name=dropbox
- user: name=dropbox uid=14564 group=dropbox

# /my/proj/ansible/roles/dropbox/docker-dropbox/ contains https://github.com/janeczku/docker-dropbox.git
  
# docker build -t bang6:5000/dropbox:latest /my/proj/ansible/roles/dropbox/docker-dropbox/

# docker run -it --rm --name=dropbox -v /home/dropbox/top/Dropbox:/dbox/Dropbox -v /home/dropbox/top/.dropbox:/dbox/.dropbox -v /home/dropbox/opt:/opt/dropbox  -e DBOX_UID=14564 -e DBOX_GID=14564 bang6:5000/dropbox:latest

- supervisor_process_mod: 
    name=dropbox
    command="docker run --rm --name=dropbox -v /home/dropbox/top/Dropbox:/dbox/Dropbox -v /home/dropbox/top/.dropbox:/dbox/.dropbox -v /home/dropbox/opt:/opt/dropbox  -e DBOX_UID=14564 -e DBOX_GID=14564 bang6:5000/dropbox:latest"
    stopasgroup=true
  notify: supervisord update

# to check DB status, set HOME=/home/dropbox then
# python ~drewp/bin/dropbox.py status
# to learn if it's syncing or whatever
