#!/bin/sh

# run as 'elastic' user

# this allows PAM to set the ulimit from /etc/security/limits.conf,
# which was not happening when supervisord runs the process itself
ulimit -Sn 1023 || exit 1

exec /usr/share/elasticsearch/bin/elasticsearch
