---
- apt: pkg=swig
- apt: pkg=scons
- apt: pkg=python-dev
- apt: pkg=build-essential


- set_fact: wsParent=/opt/piNode_ws2812-rpi
  name: start ws2812 build
- file: path={{wsParent}} state=directory
- unarchive: src=rpi_ws281x-master.zip dest={{wsParent}}
- set_fact: ws={{wsParent}}/rpi_ws281x-master

- command: scons          chdir={{ws}} creates={{ws}}/libws2811.a
- command: /opt/piNode_env/bin/easy_install -U setuptools
- name: absolute paths in python build files
  replace: dest={{ws}}/python/rpi_ws281x.i regexp="\.\./ws2811\.h" replace="{{ws}}/ws2811.h"
- replace: dest={{ws}}/python/setup.py regexp="\.\./\." replace="{{ws}}"
- command: /opt/piNode_env/bin/pip install . chdir={{ws}}/python 
