---

- apt: pkg=swap-cwm
- apt: pkg=libleveldb1v5
- file: path=/opt/ruler/server_store state=directory owner=drewp
- supervisor_process_mod:
    name=ruler_server_8102
    directory=/my/proj/ruler/server
    command="/my/proj/ruler/bin/python /my/proj/ruler/server/server.py"
    user=drewp
  notify:
   - supervisord update

# assume servers are also hosts where you might edit the config     
- supervisor_process_mod:
    name=ruler_reloader
    directory=/my/proj/ruler
    command="/my/proj/ruler/bin/python /my/proj/ruler/reloader.py"
    user=drewp
  notify:
   - supervisord update
