---
- set_fact: job=xidle port=9107 image_tag="latest"
- set_fact: base_image_platform="{{'pi' if ansible_architecture=='armv7l' else 'x86'}}"
- set_fact: image=bang6:5000/{{job}}_{{base_image_platform}}:{{image_tag}}
- docker_image: name={{image}} force=yes

- supervisor_process_mod:
    name=xidle_9107
    directory=/my/proj/homeauto/service/xidle
    command="/my/proj/homeauto/service/xidle/{{ 'bin/python' if ansible_architecture == 'x86_64' else 'env32/bin/python' }} xidle.py"
    environment=DISPLAY=:0,XAUTHORITY=/home/drewp/.Xauthority
    user=drewp
  notify: supervisord update
