---

- file: path=/opt/elastic-data owner=1000

- supervisor_process_mod: 
    name=elastic_9200
    user=drewp
    command="docker run --name elastic --rm -p 9200:9200 -p 9300:9300 -e \"ES_JAVA_OPTS=-Xms512m -Xmx512m\" -e \"discovery.type=single-node\" -e \"cluster.name=bigasterisk\" -e \"node.name=bang\" -v /opt/elastic-data:/usr/share/elasticsearch/data docker.elastic.co/elasticsearch/elasticsearch:6.4.0"
    # see http://www.elasticsearch.org/tutorials/2011/04/06/too-many-open-files.html and
    # http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/ and
    # /etc/security/limits.conf
  notify: supervisord update

- apt: pkg=jq
  
- cron:
    name="elastic_docs"
    user="drewp"
    special_time="hourly"
    job="curl -s -XPOST 'http://localhost:9060/write?db=main' --data-binary 'elastic,state=docs value='`curl -s http://bang:9200/_stats | jq '._all.total.docs.count'`"

- cron:
    name="elastic_store_bytes"
    user="drewp"
    special_time="hourly"
    job="curl -s -XPOST 'http://localhost:9060/write?db=main' --data-binary 'elastic,state=store_bytes value='`curl -s http://bang:9200/_stats | jq '._all.total.store.size_in_bytes'`"
