#!/bin/sh
export EASY_RSA=/my/proj/ansible/roles/openvpn_server/files/new
export OPENSSL="openssl"
export PKCS11TOOL="pkcs11-tool"
export GREP="grep"

export KEY_CONFIG='/my/proj/ansible/roles/openvpn_server/files/new/openssl-1.0.0.cnf'
export KEY_DIR="/etc/openvpn/keys"

# PKCS11 fixes
export PKCS11_MODULE_PATH="dummy"
export PKCS11_PIN="dummy"

export KEY_SIZE=2048

# In how many days should the root CA key expire?
export CA_EXPIRE=3650

# In how many days should certificates expire?
export KEY_EXPIRE=3650

# These are the default values for fields
# which will be placed in the certificate.
# Don't leave any of these fields blank.
export KEY_COUNTRY="US"
export KEY_PROVINCE="CA"
export KEY_CITY="SanFrancisco"
export KEY_ORG="Fort-Funston"
export KEY_EMAIL="drewp@bigasterisk.com"
export KEY_OU="bigasterisk"

# X509 Subject Field
export KEY_NAME="EasyRSA"

# If you'd like to sign all keys with the same Common Name, uncomment the KEY_CN export below
# You will also need to make sure your OpenVPN server config has the duplicate-cn option set
# export KEY_CN="CommonName"

/my/proj/ansible/roles/openvpn_server/files/new/pkitool $1
