---

- set_fact: job=audio_input_levels image_tag="latest"
- set_fact: base_image_platform="{{'pi' if ansible_architecture=='armv7l' else 'x86'}}"
- set_fact: image=bang6:5000/{{job}}_{{base_image_platform}}:{{image_tag}}
- docker_image: name={{image}} force=yes


# set pulse_input with a value from
# pactl list sources | grep Name

- supervisor_process_mod:
    name={{job}}
    command="docker run --name {{job}} --rm --mount type=bind,source=/etc/pulse,target=/etc/pulse  --mount type=bind,source=/tmp/pulseaudio,target=/tmp/pulseaudio --net=host {{image}} python ./audioInputLevelsPulse.py --source {{pulse_input}}"
    user=drewp
    autostart=true
  notify: supervisord update
  
- copy:
    dest="/var/lib/ruler.d/audio_input_levels_{{ansible_hostname}}.n3"
    content="@prefix {{':'}} <http://bigasterisk.com/ruler/ns#> .\n@prefix check{{':'}} <http://bigasterisk.com/ruler/check/> .\n@prefix host{{':'}} <http://bigasterisk.com/ruler/host/> .\ncheck:influx_audioLevel_{{ansible_hostname}}        a :InfluxDbCheck; :runHost host:bang; :measurement \"audioLevel\";    :where \"location = '{{ansible_hostname}}'\"; :dataSince \"2m\" ."
  delegate_to: bang
#  notify: ruler update
