---

- apt: pkg=build-essential
- apt: pkg=python-dev

- file: state=directory path=/opt/cam
- synchronize: src=/my/proj/webcam_pi/ dest=/opt/cam archive=yes delete=yes
- pip:
    chdir=/opt/cam
    requirements=/opt/cam/requirements.txt
    virtualenv=/opt/cam_env

# these in /boot/config.txt
# gpu_mem=128 
# start_x=1


- supervisor_process_mod:
    name=cam_8208
    directory=/opt/cam
    autostart=true
    user=root
    command="/opt/cam_env/bin/python picamserve"
  notify: supervisord update
