---
- file: path=/var/cache/photo state=directory

- apt: pkg=nfs-common
- apt: pkg=libxslt1.1
- apt: pkg=ffmpeg

- mount: fstype=nfs name=/var/cache/photo src=bang:/var/cache/photo state=mounted
  when: inventory_hostname != "bang"

- supervisor_process_mod:
    name=photo_worker
    directory=/my/site/photo/
    command="/my/site/photo/bin/celery worker"
    user=drewp
  notify: supervisord update
