FROM bang6:5000/base_pi

WORKDIR /opt/

RUN wget https://dl.influxdata.com/telegraf/releases/telegraf_1.14.1-1_armhf.deb
RUN dpkg -i telegraf_*_armhf.deb
RUN apt-get install -y lm-sensors iputils-ping
