---

- lineinfile: path=/etc/resolv.conf regex="8\.8\.8\.8" line="nameserver 8.8.8.8"

- apt: pkg=docker.io state=absent

- apt:
    pkg:
      - python-docker
      - apt-transport-https
  
- apt_key: url="https://download.docker.com/linux/raspbian/gpg"
  when: ansible_distribution == "Debian"
- apt_repository: repo="deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable"
  when: ansible_distribution == "Debian"

- apt_key: url="https://download.docker.com/linux/ubuntu/gpg"
  when: ansible_distribution != "Debian"
- apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  when: ansible_distribution != "Debian"

# don't try to get aufs-dkms on rpi-- https://github.com/docker/for-linux/issues/709
- apt: pkg=docker-ce install_recommends=no
  notify: "restart docker"

- copy: dest=/etc/docker/daemon.json content='{ "insecure-registries":["bang6:5000","bang:5000"] }'
  notify: "restart docker"

#notify wasn't running soon enough, and we need docker config in the next role, so here's an extra restart
- service: name=docker state=restarted

- lineinfile: path=/etc/resolv.conf regex="8\.8\.8\.8" line="#nameserver 8.8.8.8"
