---

- lineinfile: path=/etc/resolv.conf regex="8\.8\.8\.8" line="nameserver 8.8.8.8"
  name: temporary dns for setup. see below for removal.

# was docker-ce but i lost that in 2020-03. trying docker.io again.
- apt: pkg=docker-ce state=absent
  name: not docker-ce pkg

- apt: pkg=python3-docker
  name: python_docker


# don't try to get aufs-dkms on rpi-- https://github.com/docker/for-linux/issues/709
- apt: pkg=docker.io install_recommends=no
  name: docker_io
  notify: "restart docker"

- command: systemctl unmask docker
  name: unmask_docker

- service: state=started name=docker
  name: docker_started
  
- copy: dest=/etc/docker/daemon.json content='{ "experimental":true, "insecure-registries":["bang6:5000", "bang5:5000","bang:5000"] }'
  name: docker_registry_config
  notify: "restart docker"

#notify wasn't running soon enough, and we need docker config in the next role, so here's an extra restart.
# but, this should run only if there were changes,
#- service: name=docker state=restarted

- lineinfile: path=/etc/resolv.conf regex="8\.8\.8\.8" line="#nameserver 8.8.8.8"
