---

- service: name=dnsmasq enabled=no state=stopped

- set_fact: job=dnsmasq port=53 image_tag="latest"
- set_fact: image=bang6:5000/{{job}}:{{image_tag}}

- file: path=/opt/dnsmasq state=directory

- set_fact: net=10.1
- file: path=/opt/dnsmasq/10.1 state=directory
- template: src=dnsmasq.conf.j2 dest=/opt/dnsmasq/10.1/dnsmasq.conf
  notify: dnsmasq restart
- template: src=hosts.j2 dest=/opt/dnsmasq/10.1/hosts
  notify: dnsmasq hup
- template: src=dhcp_hosts.j2 dest=/opt/dnsmasq/10.1/dhcp_hosts
  notify: dnsmasq hup

- set_fact: net=10.2
- file: path=/opt/dnsmasq/10.2 state=directory
- template: src=dnsmasq.conf.j2 dest=/opt/dnsmasq/10.2/dnsmasq.conf
  notify: dnsmasq restart
- template: src=hosts.j2 dest=/opt/dnsmasq/10.2/hosts
  notify: dnsmasq hup
- template: src=dhcp_hosts.j2 dest=/opt/dnsmasq/10.2/dhcp_hosts
  notify: dnsmasq hup

- docker_container:
    name: "dnsmasq_10_1"
    image: "{{image}}"
    volumes:
      - "/opt/dnsmasq/10.1:/opt/dnsmasq"
    network_mode: host
    capabilities:
      - NET_BROADCAST
    privileged: "yes"
    restart_policy: always

- docker_container:
    name: "dnsmasq_10_2"
    image: "{{image}}"
    volumes:
      - "/opt/dnsmasq/10.2:/opt/dnsmasq"
    network_mode: host
    capabilities:
      - NET_BROADCAST
    privileged: "yes"
    restart_policy: always

# old dnscache comes from link in /etc/service/dnscache -> /etc/sv/dnscache
