# my global config
global:
  scrape_interval:     1m
  evaluation_interval: 1m
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hosts'
    static_configs:
      - targets:
        - 'bed5:9273'
        - 'changing5:9273'
        - 'dash5:9273'
        - 'frontbed5:9273'
        - 'frontdoor5:9273'
        - 'garage5:9273'
        - 'kitchen5:9273'
        - 'living5:9273'
        - 'prime5:9273'
        - 'workshop5:9273'
  - job_name: 'bang'
    static_configs:
      - targets:
          # telegraf
        - '172.19.0.3:9273'
  - job_name: 'intermittent_hosts'
    static_configs:
      - targets:
        - 'dot5:9273'
        - 'piedmont5:9273'
        - 'plus5:9273'
        - 'slash5:9273'
        
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
