---
- supervisor_process_mod:
    name=dpms_9095
    directory=/my/proj/homeauto/service/dpms
    command="/my/proj/homeauto/service/dpms/{{ 'bin/python' if ansible_architecture == 'x86_64' else 'env32/bin/python' }} dpms.py"
    environment=DISPLAY=:0
    user=drewp
  notify: supervisord update
