---
- supervisor_process_mod:
    name=dpms_9095
    directory=/my/proj/homeauto/service/dpms
    command="/my/proj/homeauto/service/dpms/{{ 'bin/python' if ansible_architecture == 'x86_64' else 'env32/bin/python' }} dpms.py"
    environment=DISPLAY=:0
    user=drewp
  notify: supervisord update



- set_fact:
    name: "{{ansible_hostname}}_dpms"
    domain: "bigasterisk.com"
    path: "/dpms/{{ansible_hostname}}/"
    upstreamTarget: "http://{{ansible_hostname.replace('brace', '[fc9d:ce7a:c40:7dac:439b:289c:dd2d:5101]')}}:9095/"
    openid: admin
    useWebsocketPath: yes

- template:
    dest=/var/lib/openid_proxy.d/{{name}}.n3
    src=openid_proxy_statements.n3.j2
  notify: openid_proxy restart    
  delegate_to: bang
