---
- set_fact: job=dpms port=9095 image_tag="latest"
- set_fact: base_image_platform="{{'pi' if ansible_architecture=='armv7l' else 'x86'}}"
- set_fact: image=bang6:5000/{{job}}_{{base_image_platform}}:{{image_tag}}
- docker_image: name={{image}} force=yes

- supervisor_process_mod:
    name="{{job}}_{{port}}"
    command="docker run --name {{job}} --rm -v /tmp/.X11-unix/:/tmp/.X11-unix/ -v /home/drewp/.Xauthority:/root/.Xauthority -p {{port}}:{{port}} --net=host {{image}}"
    user=drewp
  notify: supervisord update

- set_fact:
    name: "{{ansible_hostname}}_{{job}}"
    domain: "bigasterisk.com"
    path: "/dpms/{{ansible_hostname}}/"
    upstreamTarget: "http://{{ansible_hostname}}.bigasterisk.com:{{port}}/"
    openid: admin
    useWebsocketPath: yes

- template:
    dest=/var/lib/openid_proxy.d/{{name}}.n3
    src=openid_proxy_statements.n3.j2
  notify: openid_proxy restart    
  delegate_to: bang
