---
- set_fact:
    ext="10.2.0.1"
    prime="162.243.138.136"

- apt: name=network-manager state=absent
- command: systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target
  name: disable sleep/suspend

    
- template:
    dest=/etc/network/interfaces
    src=interfaces.j2
    owner=root
    group=root
    mode=0644
  notify: wifi net reset

- name: external address for nginx config
  copy:
    dest=/etc/nginx/external_address_mapping.conf
    content="# written by /my/proj/ansible/roles/network_bigasterisk_gateway/tasks/main.yml{{'\n'}}  {{ext}}/32 bang;{{'\n'}}"
    owner=root
    group=root
  notify: nginx update
  # this could perhaps go in /var/lib/nginx.d but watch out for a
  # cleaner removing all non-website files from there

- apt: pkg=iptables
  
- template:
    dest=/etc/network/firewall-setup
    src=firewall-setup.j2
    owner=root
    group=root
    mode=0755
  
- name: external address for firewall-setup
  copy:
    dest=/etc/network/firewall-setup.publicaddr
    content="# written by /my/proj/puppet/ansible/roles/network_bigasterisk_gateway/tasks/main.yml{{'\n'}}PUBLIC_ADDR={{ext}}{{'\n'}}"
    mode=644
    owner="root"
    group="root"
  notify: firewall setup

- name: firewall-setup in rc.local
  lineinfile:
    dest: /etc/rc.local
    insertbefore: "exit 0"
    line: "/etc/network/firewall-setup"
    regexp: "firewall-setup"

- name: write resolv.conf with fallback
  copy: dest=/etc/resolv.conf content="nameserver 10.2.0.1{{'\n'}}nameserver 8.8.8.8{{'\n'}}domain bigasterisk.com{{'\n'}}" force=yes
  tags: ['resolvconf']

  
# also when the IP changes:
#  /my/proj/netbars/netbars/traffic.py needs editing
#  install/restart netbars
#  change nameservers at namecheap, including ns20.quickwitretort.com which they don't normally show
#  change @ hover.com
#  change rdns at sonic   
  
- include: dhcp.yml
  tags: ['dhcp']


- name: write final resolv.conf
  copy: dest=/etc/resolv.conf content="nameserver 10.2.0.1{{'\n'}}domain bigasterisk.com{{'\n'}}" force=yes
  tags: ['resolvconf']

- apt: pkg=openntpd
- apt: pkg=ntpdate

- copy: dest=/etc/timezone content="America/Los_Angeles"
- command: "dpkg-reconfigure --frontend noninteractive tzdata"

- apt: pkg=nfs-kernel-server
  tags: ['nfs']
- copy: dest=/etc/exports content="/var/cache/photo dash(sync,rw,no_subtree_check) 10.1.0.229(sync,rw,no_subtree_check) 10.1.0.21(sync,rw,no_subtree_check)\n"
  tags: ['nfs']


# homephone is 
# 10.2.0.40 from 00:0b:82:c7:a8:cb on ens6
# on ports udp/5004 (and udp/5005, tcp/59293)
# run this (https://github.com/automatthias/hfsc/blob/master/hfsc, modified) to do traffic shaping:
#   sudo ../files/hfsc start 
# run this to view classes:
#   watch -d ../files/hfsc status 
