---
- apt: pkg=git
- apt: pkg=libao-dev
- apt: pkg=libssl-dev
- apt: pkg=libcrypt-openssl-rsa-perl
- apt: pkg=libio-socket-inet6-perl
- apt: pkg=libwww-perl
- apt: pkg=avahi-utils
- apt: pkg=libmodule-build-perl
- apt: pkg=cpanminus
- cpanm: name=Net::SDP
- git: repo=https://github.com/hendrikw82/shairport.git dest=/opt/shairport
- command: make chdir=/opt/shairport

- set_fact: ao_dev=0
- set_fact: ao_dev=1
  when: ansible_hostname == 'kitchen'
- set_fact: ao_dev=1
  when: ansible_hostname == 'living'

- copy: dest=/opt/shairport/start content="#!/bin/sh\nsystemctl restart avahi-daemon.service\nexec sudo -u drewp perl ./shairport.pl -a {{ansible_hostname}} --ao_deviceid={{ao_dev}}\n" mode=755

- supervisor_process_mod:
    name=shairport
    user=root
    directory=/opt/shairport
    command="/opt/shairport/start"
  notify:
    - supervisord update
  
